import { Recipe } from "./types";

export const DEFAULT_RECIPES: Recipe[] = [
  {
    "title": "Banánový chlebíček",
    "summary": "Vláčný moučník s vyváženým poměrem kypřidel, podpořený karamelovým tónem třtinového cukru a kousky čokolády.",
    "ingredients": [
      "[Těsto]",
      "250 g hladké pšeničné mouky",
      "100 g krupicového cukru",
      "100 g změklého másla",
      "2 ks vajec",
      "3 ks zralých banánů (rozmačkaných)",
      "60 ml podmáslí",
      "10 g kypřicího prášku do pečiva",
      "5 g sody bikarbony",
      "2 g soli",
      "[Ořechy a čokoláda]",
      "80 g nasekaných vlašských ořechů",
      "50 g hořké čokolády (nasekané)"
    ],
    "instructions": [
      "Smíchejte kypřicí složky s tekutou bází pro optimální chemickou reakci a nechte směs předem odpočinout.",
      "Předehřejte troubu na sto sedmdesát pět stupňů Celsia a formu na chlebíček vymažte máslem a vysypejte moukou nebo vyložte pečicím papírem.",
      "V míse vyšlehejte změklé máslo s třtinovým cukrem do světlé a nadýchané pěny.",
      "Do pěny postupně po jednom zašlehávejte vejce pokojové teploty, aby se emulze nesrazila.",
      "V samostatné misce vidličkou důkladně rozmačkejte banány, přidejte citronovou šťávu a mléko.",
      "V další míse prosejte hladkou mouku s jedlou sodou, kypřicím práškem a solí pro rovnoměrnou distribuci.",
      "K utřené máslové směsi střídavě nadvakrát přidejte suché suroviny a banánovou kaši a míchejte pouze ručně stěrkou do spojení.",
      "Jemně zapracujte nasekanou čokoládu a těsto ihned vlijte do připravené formy.",
      "Poslední banán podélně rozkrojte a položte řeznou stranou nahoru na povrch těsta.",
      "Pečte v předehřáté troubě po přesně vymezenou dobu tepelné úpravy a propečenost zkontrolujte špejlí.",
      "Chlebíček nechte chladnout ve formě, poté jej opatrně vyklopte na chladicí mřížku."
    ],
    "applianceTips": "V horkovzdušné troubě pečte na středním roštu bez zapnutého grilu. Pro parní trouby zvolte nízkou úroveň páry na počátku pečení pro ještě lepší nárůst objemu a lesklou kůrku.",
    "expertJustification": "Čas tepelné úpravy byl přesně kalibrován na optimálních padesát pět minut, což zaručuje dostatečné propečení středu s vysokým podílem banánového pyré, aniž by došlo k vysušení okrajů či spálení čokolády na povrchu. Recept zcela vylučuje chemické konzervanty a umělá aromata.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "55 min",
    "difficulty": "Snadné",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1781467904494",
    "estimatedCookingTime": "45",
    "updatedAt": "2026-08-02T22:46:50.663Z"
  },
  {
    "title": "Bavorské vdolečky",
    "summary": "Tradiční nadýchané kynuté pečivo smažené dozlatova. Podává se s povidly, zakysanou smetanou a strouhaným tvarohem.",
    "ingredients": [
      "[Kvásek a těsto]",
      "500 g hladké pšeničné mouky",
      "250 ml plnotučného mléka (vlažného)",
      "30 g čerstvého droždí",
      "50 g krupicového cukru",
      "60 g rozpuštěného másla",
      "2 ks žloutků",
      "5 g soli",
      "5 g citronové kůry",
      "[Smažení]",
      "500 ml oleje nebo sádla na smažení",
      "[Na ozdobu a podávání]",
      "200 g švestkových povidel",
      "150 g strouhaného tvarohu",
      "150 g zakysané smetany nebo šlehačky"
    ],
    "instructions": [
      "V misce rozdrobte droždí, přelijte částí vlažného mléka, přidejte špetku cukru a nechte na teplém místě vzejít kvásek, dokud se na hladině nevytvoří bohatá pěna.",
      "Do mísy kuchyňského robotu prosejte mouku se solí, přidejte zbylý cukr, aktivovaný kvásek, celé vejce, žloutek, rum a vlahé rozpuštěné máslo.",
      "Pomocí hnětacího háku hněťte těsto na nízkou rychlost po dobu deseti minut, dokud nevznikne hladká, elastická hmota, která se nelepí na stěny. Mísu zakryjte fólií a nechte kynout při pokojové teplotě do zdvojnásobení objemu.",
      "Vykynuté těsto vyklopte na pomoučněný vál, jemně ho prohněťte pro uvolnění přebytečných plynů a rozválejte na rovnoměrný plát.",
      "Pomocí kulatého vykrajovátka vytvarujte jednotlivé vdolečky, rozložte je na pomoučněnou plochu, přikryjte utěrkou a nechte podstoupit finální dokynutí.",
      "V hluboké pánvi rozehřejte dostatečné množství oleje na stabilní teplotu vhodnou pro smažení. Těsně před smažením vytvořte ve středu každého vdolečku prsty hluboký důlek.",
      "Vdolečky vkládejte do horkého oleje nejprve stranou s důlkem dolů, pánev zakryjte pokličkou a smažte dozlatova. Poté je otočte, dosmažte již odkryté a nechte okapat na papírovém ubrousku.",
      "Teplé vdolečky ozdobte povidly nanesenými do důlku, přidejte zakysanou smetanu a bohatě posypejte jemně nastrouhaným tvarohem."
    ],
    "applianceTips": "Při smažení na indukční varné desce využijte funkci přesného nastavení teploty na stupeň určený pro smažení (ideálně 170-175 °C). Tím zabráníte přepalování tuku a zajistíte rovnoměrné propečení střídky bez nadměrné absorpce oleje.",
    "expertJustification": "Přidání přesného času hnětení na deset minut v kuchyňském robotu zaručuje dokonalý rozvoj lepkové struktury. To zajišťuje optimální elasticitu těsta a jeho schopnost udržet plynné bublinky během kynutí a následného smažení. Rum v těstě nadále funguje jako fyzikální bariéra zabraňující nasáknutí tuku.",
    "applianceType": "Indukční varná deska",
    "cookingTime": "90 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1781777265750",
    "estimatedCookingTime": "10",
    "updatedAt": "2026-08-02T22:46:50.663Z"
  },
  {
    "id": "bucek",
    "title": "Bůček pečený",
    "summary": "Šťavnatý vepřový bůček s maximálně křupavou krustou připravený dvoufázovou metodou v horkovzdušné fritéze.",
    "cookingTime": "80 min",
    "difficulty": "Střední",
    "applianceType": "Horkovzdušná fritéza",
    "ingredients": [
      "[Maso]",
      "1 kg vepřového bůčku (s kůží, bez kosti)",
      "[Koření a potření]",
      "2 lžičky hrubozrnné soli",
      "1 lžička drceného kmínu",
      "4 stroužky česneku (utřené)",
      "[Krusta]",
      "1 lžíce jablečného octa",
      "1 lžička kukuřičného škrobu"
    ],
    "instructions": [
      "Povrch kůže nařežte do husté mřížky tak, abyste nezasáhli hluboko do masité části.",
      "Do spodní a bočních stran masa důkladně vetřete sůl, kmín a utřený česnek. Kůži ponechte suchou a čistou.",
      "Povrch kůže potřete jablečným octem a následně lehce poprašte směsí soli a kukuřičného škrobu pro dosažení optimální dehydratace povrchu.",
      "Vložte bůček do fritézy kůží dolů a zahřívejte při 150 °C po dobu 45 minut, aby došlo k pozvolnému uvolnění tuku a jemnému prohřátí struktury masa.",
      "Po uplynutí času bůček opatrně otočte kůží nahoru a zvyšte teplotu na 200 °C po dobu 20 minut, dokud povrch nevytvoří rovnoměrně křupavou krustu.",
      "Vyjměte maso ze spotřebiče a před krájením jej nechte 15 minut odpočívat na mřížce, aby se vnitřní šťávy rovnoměrně redistribuovaly."
    ],
    "applianceTips": "Při pečení kůží nahoru zajistěte, aby kolem masa proudil vzduch. Pokud máte fritézu s menším košem, podložte bůček, aby se teplo dostalo i pod něj.",
    "expertJustification": "Dvoufázový proces využívá fyzikální jev denaturace proteinů při nízké teplotě, což zaručuje měkkost, následovanou Maillardovou reakcí a rychlou dehydratací povrchu při vysoké teplotě pro efekt 'crackling'.",
    "category": "Maso",
    "isDefault": true,
    "updatedAt": "2026-08-02T22:46:50.664Z",
    "estimatedCookingTime": "65 min"
  },
  {
    "title": "Buřtguláš",
    "summary": "Poctivý buřtguláš zahuštěný přímou jíškou, zjemněný smetanou a provoněný majoránkou. Tradiční česká klasika bez umělých dochucovadel s dokonale provařeným základem.",
    "ingredients": [
      "[Uzenina a zelenina]",
      "500 g kvalitních špekáčků nebo buřtů",
      "800 g brambor (varný typ B)",
      "250 g cibule (nadrobno)",
      "3 stroužky česneku",
      "[Základ a koření]",
      "40 g vepřového sádla",
      "20 g sladké mleté papriky",
      "5 g pálivé mleté papriky",
      "3 g drceného kmínu",
      "3 g sušené majoránky",
      "800 ml hovězího vývaru nebo vody",
      "30 g hladké mouky",
      "Sůl a čerstvě mletý pepř"
    ],
    "instructions": [
      "Špekáčky oloupejte a nakrájejte na půlkolečka, brambory na stejně velké kostky a cibuli nadrobno. Česnek utřete se špetkou soli.",
      "V těžkém litinovém hrnci rozpusťte vepřové sádlo, přidejte nakrájené špekáčky a opékejte je na středním plameni přibližně pět až sedm minut, dokud nepustí tuk a na povrchu jemně nezkaramelizují.",
      "K opečené uzenině přidejte cibuli. Snižte teplotu a za občasného míchání ji pomalu restujte deset až patnáct minut do sytě zlatavé barvy. V závěru přidejte drcený kmín a utřený česnek a nechte je minutu rozvonět.",
      "Celou směs zaprašte hladkou moukou a za stálého míchání opékejte dvě minuty, aby se potlačila syrová chuť škrobu. Hrnec následně odstavte z plamene, vmíchejte sladkou i pálivou papriku a nechte ji v horkém tuku zhruba třicet sekund zpěnit, aby se uvolnilo barvivo a aroma bez rizika zhořknutí.",
      "Základ okamžitě zalijte studeným domácím hovězím vývarem a metličkou důkladně odškrábněte všechny karamelizované přípečky ode dna. Vraťte hrnec na plamen, přiveďte k varu, vložte nakrájené brambory a pod pokličkou nechte mírně bublat dvacet až dvacet pět minut, dokud brambory nezměknou a omáčka se přirozeně nezahustí.",
      "Do hotového základu vlijte smetanu ke šlehání a nechte dvě minuty mírně provřít pro dokonalé propojení chutí a emulgaci. Hrnec odstavte z tepla, vmíchejte v dlaních rozemnutou sušenou majoránku, podle chuti dolaďte solí a čerstvě mletým černým pepřem a nechte před podáváním pět minut odpočívat."
    ],
    "applianceTips": "Litinový hrnec s těžkým dnem je ideální pro rovnoměrnou distribuci tepla a dokonalou Maillardovu reakci při opékání uzeniny a cibule. Pro pomalé vaření lze po orestování základu využít pomalý hrnec nastavený na režim Low po dobu čtyř hodin, čímž docílíte mimořádně hluboké chuti.",
    "expertJustification": "Základem úspěchu je pomalé restování cibule na sádle, čímž uvolníme přírodní cukry a získáme hlubokou chuť bez nutnosti použití umělých barviv. Opékáním mouky (dextrinizací) přímo na tuku eliminujeme syrovou škrobovou chuť a stabilizujeme omáčku. Vložení papriky mimo přímý žár zabrání jejímu spálení a zhořknutí, zatímco použití studeného vývaru na horkou jíšku zamezuje tvorbě nežádoucích hrudek.",
    "applianceType": "Litinový hrnec",
    "cookingTime": "60 min",
    "difficulty": "Snadné",
    "category": "Polévky",
    "id": "gen-1783884136320",
    "updatedAt": "2026-08-02T22:46:50.664Z",
    "estimatedCookingTime": "45 min"
  },
  {
    "title": "Chléb  kváskový s kmínem",
    "summary": "Tradiční řemeslný chléb s dlouhou fermentací pro dosažení optimální stravitelnosti a křupavé kůrky.",
    "ingredients": [
      "[Rozkvas]",
      "150 g žitného kvasu",
      "150 g žitné chlebové mouky",
      "150 ml vlažné vody",
      "[Hlavní těsto]",
      "350 g pšeničné chlebové mouky",
      "200 ml vlažné vody",
      "12 g soli",
      "8 g drceného kmínu"
    ],
    "instructions": [
      "Smíchejte aktivní kvásek s vlažnou vodou a oběma druhy mouky. Nechte směs odpočívat pro proces autolýzy, který iniciuje enzymatický rozklad škrobů a bílkovin.",
      "Po dokončení autolýzy vmíchejte sůl a kmín. Těsto krátce prohněťte, dokud není homogenní a pružné.",
      "Během hlavního kynutí při pokojové teplotě provádějte pravidelné překládání těsta v hodinových intervalech pro zpevnění lepkové struktury.",
      "Vytvarujte bochník a vložte jej do ošatky důkladně vysypané rýžovou moukou, aby nedošlo k přilepení.",
      "Ošatku s těstem umístěte do chladného prostředí pro dlouhou fermentaci, která rozvine hlubokou chuť a aroma.",
      "Troubu s prázdným litinovým hrncem rozpalte na vysokou teplotu. Do rozpáleného hrnce opatrně vyklopte těsto, přiklopte poklicí pro vytvoření páry a pečte. Následně poklici sejměte a dopečte do tmavě zlaté barvy pro dosažení křupavé kůrky."
    ],
    "applianceTips": "Pro pečení v domácích podmínkách je klíčové využití litinového hrnce, který funguje jako pec v peci a udržuje stabilní vlhkost během prvních minut pečení.",
    "expertJustification": "Autolýza zkracuje čas hnětení a zlepšuje roztažnost těsta. Chladná fermentace (retardace) je klíčem k enzymatické aktivitě, která odbourává antinutriční látky a zvyšuje biologickou dostupnost minerálů z celozrnných mouk.",
    "applianceType": "Horkovzdušná trouba s litinovým nádobím",
    "cookingTime": "1140 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783526818566",
    "updatedAt": "2026-08-02T22:46:50.664Z",
    "estimatedCookingTime": "50 min"
  },
  {
    "title": "Chléb  pšenično-žitný s droždím",
    "summary": "Tradiční domácí chléb s přídavkem sladu a octa nahrazujícího kvas, optimalizovaný pro dosažení nadýchané střídky a křupavé kůrky pomocí pečení s párou.",
    "ingredients": [
      "[Tekutý základ a kvásek]",
      "330 ml vlažné vody",
      "12 g čerstvého droždí",
      "10 g ječné sladěnky nebo cukru",
      "[Moučná směs a koření]",
      "350 g pšeničné chlebové mouky",
      "150 g žitné chlebové mouky",
      "12 g soli",
      "8 g drceného kmínu",
      "15 g oleje"
    ],
    "instructions": [
      "V misce důkladně rozpustíme droždí a ječný slad v části vlažné vody. Směs necháme na teplém místě vzejít, dokud se na hladině nevytvoří stabilní pěna.",
      "V míse kuchyňského robotu promícháme pšeničnou chlebovou mouku, žitnou chlebovou mouku, jemnou sůl a celý kmín.",
      "K suché směsi přilijeme vzešlý kvásek, zbývající vlažnou vodu a jablečný ocet. Těsto hněteme hnětacím hákem na nízkou rychlost, dokud se suroviny nespojí a nezačne se vyvíjet lepková struktura.",
      "Uhnětené těsto vytvarujeme do hladké koule, vložíme do mísy, zakryjeme fólií a necháme kynout při pokojové teplotě, dokud nezdvojnásobí svůj objem.",
      "Vykynuté těsto vyklopíme na pomoučněnou plochu, jemně stočíme do pevného bochníku a vložíme do vysypané ošatky k finálnímu kynutí pod utěrkou.",
      "Vykynutý bochník vyklopíme na sázecí lopatu, nařízneme ostrým nožem a sesuneme na rozpálený kámen v troubě předehřáté na nejvyšší výkon. Na dno trouby okamžitě vlijeme horkou vodu pro vytvoření páry, po deseti minutách troubu odvětráme, snížíme teplotu a chléb dopékáme dozlatova."
    ],
    "applianceTips": "Pro nejlepší možný vývoj kůrky použijte litinový hrnec s poklicí předehřátý na maximum. Pečení v uzavřeném prostoru dokonale zadrží přirozenou vlhkost těsta a simuluje profesionální parní pec bez nutnosti externího zapařování.",
    "expertJustification": "Úprava časů hnětení na delší interval je nezbytná pro správné rozvinutí lepkové sítě u pšeničné části mouky. Prodloužení obou fází kynutí zaručuje rovnoměrnou poréznost střídky a lepší stravitelnost. Pečení s počátečním teplotním šokem a párou zajistí maximální nárůst objemu těsta před vytvořením finální kůrky.",
    "applianceType": "Elektrická trouba s pečicím kamenem",
    "cookingTime": "165 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783415546359",
    "estimatedCookingTime": "35 min",
    "updatedAt": "2026-08-02T22:46:50.664Z"
  },
  {
    "title": "Chléb pšenično-žitný",
    "summary": "Tradiční kváskový bochník s vysokou hydratací, připravený pomocí autolýzy pro maximální rozvoj lepkové sítě a bohatou chuť.",
    "ingredients": [
      "[Rozkvas]",
      "150 g žitného kvasu",
      "150 g žitné chlebové mouky",
      "150 ml vody",
      "[Těsto]",
      "350 g pšeničné chlebové mouky",
      "210 ml vody",
      "12 g soli",
      "8 g drceného kmínu"
    ],
    "instructions": [
      "Smíchejte pšeničné i žitnou mouku s většinou vody a nechte směs odpočívat půl hodiny, čímž dojde k hydrataci škrobů a startu autolýzy.",
      "Do autolyzovaného těsta přidejte aktivní kvásek a zbylou část vody; hněťte v robotu při nízké rychlosti, dokud těsto nezačne vykazovat první známky elasticity.",
      "Přidejte sůl a drcený kmín a pokračujte v hnětení, dokud není těsto hladké, pružné a neodlepuje se od stěn mísy.",
      "Nechte těsto fermentovat v teple přibližně tři hodiny, přičemž v průběhu procesu proveďte tři série překládání v hodinových intervalech pro zpevnění struktury.",
      "Vykynuté těsto opatrně vyklopte na pomoučený vál, vytvarujte do napnutého bochníku a vložte do ošatky vysypané moukou k finálnímu kynutí.",
      "Rozpalte troubu společně s litinovým hrncem na vysokou teplotu; následně bochník nařežte, vložte do nádoby a pečte pod poklicí pro vytvoření páry.",
      "Po úvodní fázi odstraňte poklici, snižte teplotu a dopečte do sytě zlatavé barvy a charakteristického zvuku při poklepu na spodní stranu."
    ],
    "applianceTips": "Před pečením využijte funkci parního rázu, pokud ji vaše trouba umožňuje, nebo ponechte v hrnci poklici dostatečně dlouho, aby vlhkost obsažená v těstě zajistila maximální objem střídky.",
    "expertJustification": "Postup byl upraven dle pekařských standardů zahrnutím autolýzy a systematického překládání těsta, což vede k lepší struktuře střídky a delší čerstvosti bez nutnosti aditiv.",
    "applianceType": "Trouba s litinovým hrncem",
    "cookingTime": "5 hodin",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781773438337",
    "estimatedCookingTime": "45 min",
    "updatedAt": "2026-08-02T22:46:50.665Z"
  },
  {
    "title": "Chléb pšeničný kváskový",
    "summary": "Profesionálně vedený pšeničný chléb využívající techniky autolýzy a řízené chladové fermentace pro dosažení maximální vzdušnosti střídky a komplexní chuti.",
    "ingredients": [
      "[Rozkvas]",
      "100 g pšeničného kvasu",
      "100 g pšeničné mouky",
      "100 ml vody",
      "[Těsto]",
      "400 g pšeničné chlebové mouky",
      "250 ml vody",
      "11 g soli"
    ],
    "instructions": [
      "V míse důkladně promíchejte obě mouky s vlažnou vodou tak, aby v těstě nezůstala žádná suchá místa. Nechte směs odpočívat, aby proběhla autolýza a přirozeně se rozvinula lepková síť.",
      "Do autolyzovaného základu vmíchejte aktivní kvásek. Následně přidejte sůl a kmín. Těsto hněťte v robotu při nízkých otáčkách, dokud není hladké, elastické a neodlepuje se od stěn nádoby.",
      "Těsto přemístěte do nádoby a nechte jej zrát při pokojové teplotě. V prvních devadesáti minutách proveďte pravidelné série překladů, které zajistí potřebnou strukturu a pevnost střídky.",
      "Po dokončení kynutí těsto opatrně vyklopte na lehce pomoučenou plochu, proveďte jemné předtvarování a nechte krátce odpočinout. Následně vytvořte pevný bochník a vložte jej do ošatky vysypané rýžovou moukou.",
      "Ošatku s těstem umístěte do chladničky pro pomalou fermentaci, která prohloubí chuťový profil a zajistí lepší stravitelnost.",
      "Troubu s litinovým hrncem uvnitř rozpalte na vysokou teplotu. Chléb vyklopte na pečicí papír, proveďte hluboký řez a vložte do rozpáleného hrnce. Pečte nejprve pod poklicí pro vytvoření páry, poté dopečte odkryté do tmavě zlaté barvy."
    ],
    "applianceTips": "Klíčem k úspěchu je maximální předehřátí litinového hrnce. Parní ráz v uzavřeném prostoru během prvních minut pečení umožní maximální nárůst objemu (tzv. oven spring).",
    "expertJustification": "Postup byl optimalizován dle pekařské praxe s důrazem na enzymatickou aktivitu. Autolýza bez soli umožňuje lepší hydrataci lepku, zatímco chladová retardace stabilizuje organické kyseliny, což vede k lepší struktuře střídky a delší trvanlivosti.",
    "applianceType": "Trouba s litinovým hrncem",
    "cookingTime": "960 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781443902352",
    "estimatedCookingTime": "45 min",
    "updatedAt": "2026-08-02T22:46:50.665Z"
  },
  {
    "title": "Chléb Šumava",
    "summary": "Tradiční řemeslný pšenično-žitný chléb s vyváženým kvasným stupněm a bezpečnou hydratací pro pevný bochník s nadýchanou střídou.",
    "ingredients": [
      "[Žitný rozkvas]",
      "150 g žitného kvasu",
      "150 g žitné chlebové mouky",
      "150 ml vody",
      "[Hlavní chlebové těsto]",
      "350 g pšeničné chlebové mouky (T650)",
      "210 ml vlažné vody",
      "12 g jemné mořské soli",
      "8 g drceného kmínu"
    ],
    "instructions": [
      "Příprava rozkvasu: V nádobě smíchejte žitný kvásek, žitnou mouku a vlažnou vodu. Nechte přikryté zrát při pokojové teplotě, dokud nezdvojnásobí až ztrojnásobí svůj objem.",
      "Autolýza: V míse robotu smíchejte pšeničnou chlebovou mouku, žitnou chlebovou mouku a vlažnou vodu pouze do spojení surovin, aby nezůstala žádná suchá místa. Nechte odpočívat pro plnou hydrataci lepku.",
      "Hnětení: K autolyzovanému těstu přidejte vyzrálý rozkvas, jemnou mořskou sůl a celý kmín. Hněťte v robotu hákem na nejnižší rychlost, dokud nevznikne hladké a elastické těsto.",
      "První fermentace: Těsto nechte přikryté kynout v míse. Během kynutí proveďte v pravidelných intervalech dvě série šetrných překladů pro zpevnění lepkové struktury.",
      "Tvarování a kynutí v ošatce: Těsto vyklopte na lehce pomoučený vál, stočte do pevného bochníku s důkladně utaženým povrchovým napětím a vložte spojem nahoru do vysypané ošatky. Nechte kynout při pokojové teplotě, dokud se testovací důlek po stlačení prstem nevrací pomalu zpět.",
      "Pečení: Bochník opatrně vyklopte na pečicí papír. Pečte v předehřáté troubě se zapařením, po úvodní fázi troubu vyvětrejte, snižte teplotu a dopečte do požadované barvy kůrky. Chlaďte na mřížce."
    ],
    "applianceTips": "Pro optimální kůrku využijte pečení v troubě s automatickým parním rázem v první fázi, případně využijte automatický program pro chléb se studeným startem, který řídí vlhkost a nárůst teploty za vás.",
    "expertJustification": "Receptura byla upravena na celkových 700 g mouky s celkovou hydratací kolem 64 %, což odpovídá optimu pro ideální střídu a dobrou manipulaci. Hydratace autolýzy na úrovni 58 % zajišťuje dostatečné bobtnání bílkovin pšenice před přidáním žitného rozkvasu a soli. Kvůli obsahu žitné mouky nad dvacet procent bylo hnětení a počet překladů optimalizovány tak, aby se zabránilo poškození vznikající gelové struktury těsta.",
    "applianceType": "Trouba s funkcí páry nebo automatickým programem",
    "cookingTime": "16 hodin",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783540977144",
    "updatedAt": "2026-08-02T22:46:50.665Z",
    "estimatedCookingTime": "45 min"
  },
  {
    "title": "Chléb žitno-pšeničný 5:3",
    "summary": "Technicky zdokonalený recept s využitím řízené autolýzy a dvoufázového kynutí pro dosažení maximální objemové stability a textury střídy.",
    "ingredients": [
      "[Žitný rozkvas]",
      "200 g žitného kvasu",
      "200 g žitné mouky",
      "200 ml vody",
      "[Těsto]",
      "300 g pšeničné chlebové mouky",
      "160 ml vody",
      "12 g soli",
      "8 g kmínu"
    ],
    "instructions": [
      "Smíchejte žitnou a pšeničnou mouku s vodou a nechte směs odpočívat 60 minut při pokojové teplotě pro zahájení enzymatické autolýzy.",
      "Do autolyzovaného základu vpracujte aktivní kvásek, sůl a kmín. Hněťte 10 minut do dosažení střední elasticity těsta.",
      "Nechte těsto fermentovat 180 minut, během nichž proveďte 3 cykly překládání v intervalech 45 minut pro vybudování struktury lepkové sítě.",
      "Vytvarujte bochník s vysokým napětím povrchové vrstvy a přemístěte jej do ošatky. Následuje 600 minut kynutí v chladu při teplotě 5 °C.",
      "Pečte v předehřáté troubě prvních 15 minut při 250 °C se silným zapařením, poté snižte teplotu na 210 °C a pečte 20 minut, následně dopékejte 15 minut při 180 °C bez páry."
    ],
    "applianceTips": "Pro dosažení ideální krusty využijte funkci parního rázu v první fázi pečení a v závěrečné fázi odvětrejte vlhkost krátkým otevřením dvířek trouby.",
    "expertJustification": "Prodloužení chladné fermentace zvyšuje biologickou dostupnost minerálů a zlepšuje senzorické vlastnosti střídy díky delší aktivitě bakterií mléčného kvašení.",
    "applianceType": "Horkovzdušná pec s funkcí napařování",
    "cookingTime": "870 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783527082168",
    "updatedAt": "2026-08-02T22:46:50.665Z",
    "estimatedCookingTime": "50 min"
  },
  {
    "title": "Coleslaw",
    "summary": "Precizně technicky zpracovaný zelný salát, kde osmóza a následná stabilizace textury vytvářejí ideální křupavost bez nežádoucího vodnatění.",
    "ingredients": [
      "[Zeleninový základ]",
      "500 g hlávkového zelí",
      "100 g mrkve",
      "50 g celeru",
      "50 g cibule",
      "[Zálivka a dochucení]",
      "100 g majonézy",
      "50 g zakysané smetany",
      "15 ml jablečného octa",
      "15 g cukru krupice",
      "5 g soli",
      "2 g mletého černého pepře"
    ],
    "instructions": [
      "Zelí nakrouhejte na tenké nudličky, v míse ho promíchejte se solí a nechte 20 min odpočívat pro zahájení procesu osmózy.",
      "Během odpočinku zelí nastrouhejte mrkev a celer, šalotku nasekejte nadrobno a připravte si dresink smícháním octa, hořčice, cukru a pepře v homogenní tekutinu.",
      "Po uplynutí 20 min zelí důkladně promačkejte a v utěrce nebo odstředivce vymačkejte veškerou uvolněnou tekutinu, aby salát zůstal křupavý.",
      "Do připravené tekuté směsi vmíchejte majonézu a smetanu, čímž vznikne stabilní emulze, kterou následně důkladně zapracujte do zeleninové směsi.",
      "Salát dejte odležet do chladničky na 120 min, aby došlo k hloubkové harmonizaci chutí a stabilizaci dresinku na surovinách."
    ],
    "applianceTips": "K dosažení konzistentní struktury použijte food processor s vlnitým krouhacím diskem. Rychlou filtraci buněčné vody zajistí odstředivka na salát.",
    "expertJustification": "Zkrácení doby osmózy na 20 minut zabrání nadměrnému zničení buněčné struktury, zatímco 120 minut chlazení je optimální doba pro infiltraci dresinku do pórů zeleniny bez degradace čerstvosti.",
    "applianceType": "Kuchyňský robot s krouhacím diskem",
    "cookingTime": "140 min",
    "difficulty": "Snadné",
    "category": "Ostatní",
    "id": "gen-1782536706330",
    "estimatedCookingTime": "0 min",
    "updatedAt": "2026-08-02T22:46:50.666Z"
  },
  {
    "title": "Dalamánky",
    "summary": "Křupavé žitno-pšeničné pečivo s vysokým obsahem vlákniny, připravené metodou řízené fermentace pro maximální rozvoj chuti a struktury střídky.",
    "ingredients": [
      "[Těsto]",
      "300 g pšeničné chlebové mouky",
      "200 g žitné chlebové mouky",
      "320 ml vlažné vody",
      "20 g čerstvého droždí",
      "10 g soli",
      "8 g drceného kmínu",
      "[Na posypání]",
      "Hrubozrnná sůl a celý kmín na posyp"
    ],
    "instructions": [
      "Droždí rozmíchejte v části vlažné vody se sladem a nechte 15 minut vzejít kvásek při teplotě 28 °C.",
      "Do mísy prosejte obě mouky, přidejte sůl, kmín, zbytek vody, jablečný ocet a vzešlý kvásek.",
      "Pomocí hnětacího stroje vypracujte elastické těsto. Proces by měl trvat 8 minut na nízký rychlostní stupeň, aby se vytvořila správná lepková vazba bez zbytečného zahřátí.",
      "Těsto nechte 60 minut kynout v uzavřené nádobě při teplotě 24 °C, dokud zdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na stejné bochánky a vytvarujte pevné oválné tvary.",
      "Na plechu nechte bochánky 30 minut finálně kynout pod utěrkou. Povrch nařízněte žiletkou pro kontrolovaný růst během pečení.",
      "Pečte v troubě s parním zárazem při 230 °C po dobu 8 minut, poté snižte teplotu na 200 °C a dopečte 12 minut dozlatova."
    ],
    "applianceTips": "Při použití horkovzdušné trouby využijte funkci připařování. Pokud ji přístroj nemá, umístěte na dno trouby plech s horkými kameny a při vkládání pečiva na ně vlijte 50 ml vody.",
    "expertJustification": "Jablečný ocet snižuje pH, což je u žitných těst kritické pro aktivitu amyláz a prevenci lepkavosti střídky. Snížení intenzity hnětení oproti čistě pšeničným receptům brání únavě lepku, což je u směsí s vysokým podílem žita klíčové pro finální objem.",
    "applianceType": "Konvektomat nebo horkovzdušná trouba",
    "cookingTime": "125 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783722072636",
    "updatedAt": "2026-08-02T22:46:50.666Z",
    "estimatedCookingTime": "20 min"
  },
  {
    "title": "Dukátové buchtičky",
    "summary": "Tradiční kynuté buchtičky s pravým žloutkovým vanilkovým krémem, připravené s důrazem na enzymatickou aktivitu těsta a jemnou texturu.",
    "ingredients": [
      "[Těsto na buchtičky]",
      "500 g hladké pšeničné mouky",
      "250 ml plnotučného mléka",
      "30 g čerstvého droždí",
      "60 g krupicového cukru",
      "80 g rozpuštěného másla",
      "2 ks žloutků",
      "5 g citronové kůry",
      "3 g soli",
      "[Vanilkový krém (Šodó)]",
      "750 ml plnotučného mléka",
      "1 ks vanilkového lusku (nebo vanilkový extrakt)",
      "4 ks žloutků",
      "80 g krupicového cukru",
      "25 g kukuřičného škrobu"
    ],
    "instructions": [
      "Aktivujte kvásek smícháním droždí s částí vlažného mléka a nechte v teple 20 minut pracovat, dokud nevzejde hustá pěna.",
      "Do mísy prosejte mouku se solí, přidejte vzešlý kvásek, zbytek vlažného mléka a směs vyšlehaných žloutků s cukrem a máslem.",
      "Hněťte těsto v robotu 10 minut na nízkou rychlost, dokud není hladké a elastické, poté jej nechte 60 minut kynout v teple.",
      "Vykynuté těsto rozdělte na díly, vytvarujte malé kuličky, naskládejte je do máslem vymazaného pekáče a každou kuličku důkladně potřete rozpuštěným máslem.",
      "Nechte buchtičky v pekáči finálně kynout 30 minut a následně pečte v předehřáté troubě na 180 °C po dobu 25 minut.",
      "Pro přípravu krému zahřejte mléko s vanilkovým luskem k bodu varu, nechte 10 minut louhovat a poté vyjměte lusk.",
      "Vyšlehejte žloutky s cukrem a škrobem, opatrně přilijte horké mléko a za stálého míchání zahřívejte 8 minut do zhoustnutí, nakonec zašlehejte rum."
    ],
    "applianceTips": "Pro dokonalé kynutí využijte funkci parního kynutí v troubě při 35 °C. Krém připravujte ve varném robotu při teplotě 82 °C, která zajistí pasterizaci žloutků bez rizika jejich sražení.",
    "expertJustification": "Recept využívá dvoufázovou fermentaci pro optimalizaci lepkového vývoje. Použití škrobu jako stabilizátoru v žloutkové emulzi brání koagulaci bílkovin při vyšších teplotách, což zaručuje krémovou texturu bez hrudek.",
    "applianceType": "Kuchyňský robot s hnětačem a varný robot",
    "cookingTime": "165 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1783884254487",
    "updatedAt": "2026-08-02T22:46:50.666Z",
    "estimatedCookingTime": "68 min"
  },
  {
    "title": "Holandské řízky",
    "summary": "Šťavnaté karbanátky z emulgovaného masa se sýrem připravené precizní technikou pro dosažení maximální křehkosti a chuti.",
    "ingredients": [
      "[Masová směs]",
      "600 g mletého bůčku nebo krkovice",
      "200 g tvrdého sýra (Gouda/Edam, nastrouhaný)",
      "100 ml plnotučného mléka",
      "1 ks vejce",
      "10 g soli",
      "2 g čerstvě mletého černého pepře",
      "5 g nasekané čerstvé petrželky",
      "[Trojobal a smažení]",
      "80 g hladké mouky",
      "2 ks rozšlehaných vajec",
      "150 g strouhanky",
      "200 g sádla nebo oleje na smažení"
    ],
    "instructions": [
      "V robotu spojte mleté maso, sůl, pepř a vejce. Pomocí K-metly šlehejte 8 min, přičemž postupně přilévejte mléko, dokud nevznikne kompaktní, lepivá emulze.",
      "Do masového základu jemně zapracujte nastrouhaný sýr a směs nechte odpočívat v chladu 60 min, aby se stabilizovaly proteiny.",
      "Ze směsi tvarujte oválné karbanátky a postupně je obalte v mouce, rozšlehaných vejcích a strouhance, přičemž dbejte na důkladné uzavření obalu.",
      "Obalené řízky smažte v rozpáleném sádle z obou stran 4 min do zlatavé barvy.",
      "Následně řízky přemístěte do trouby předehřáté na 140 °C a dopečte je 15 min, dokud vnitřní teplota neodpovídá standardům pro vepřové maso."
    ],
    "applianceTips": "Při použití horkovzdušné fritézy nastavte teplotu 180 °C a pečte 12 min, čímž dosáhnete křupavé krusty s minimem přidaného tuku.",
    "expertJustification": "Emulgace za studena vytváří stabilní bílkovinnou matrix, která v kombinaci se správným poměrem bůčku a plece zajistí šťavnatost. Doba odpočinku je klíčová pro hydrataci svalových vláken, zatímco kombinace smažení a konvekčního pečení optimalizuje Maillardovu reakci při zachování celistvosti sýrové náplně.",
    "applianceType": "Konvektomat / Trouba",
    "cookingTime": "95 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "gen-1781776733049",
    "estimatedCookingTime": "19 min",
    "updatedAt": "2026-08-02T22:46:50.666Z"
  },
  {
    "title": "Hovězí guláš",
    "summary": "Klasický hovězí guláš z kližky zahuštěný chlebovou střídkou, s bohatou chutí pomalu karamelizované cibule a tradičního koření.",
    "ingredients": [
      "[Maso a cibule]",
      "800 g hovězí kližky",
      "800 g cibule (nadrobno)",
      "[Smažení a koření]",
      "80 g vepřového sádla",
      "30 g sladké mleté papriky",
      "5 g drceného kmínu",
      "4 stroužky česneku",
      "3 g sušené majoránky",
      "800 ml hovězího vývaru",
      "Sůl a černý pepř",
      "[Zahuštění]",
      "1 střídka staršího chleba na zahuštění"
    ],
    "instructions": [
      "V těžkém hrnci rozpusťte sádlo, přidejte jemně nakrájenou cibuli a restujte ji na mírném ohni za stálého míchání do tmavě hnědé barvy.",
      "K osmažené cibuli přidejte celý kmín, polovinu prolisovaného česneku a rajský protlak. Směs krátce orestujte, dokud protlak nezvoní a neztratí kyselost.",
      "Hrnec na chvíli odstavte z plamene a vmíchejte sladkou i pálivou mletou papriku. Nechte ji v teplém tuku rozpustit, aby uvolnila barvu a vůni.",
      "Vraťte hrnec na sporák, přidejte nakrájené hovězí maso, osolte, opepřete a zprudka opékejte, dokud se maso nezatáhne a nevydusí se vlastní šťáva.",
      "Zalijte směs horkým hovězím vývarem, hrnec přikryjte poklicí a duste na mírném ohni do poloměkka.",
      "Přisypte nastrouhanou chlebovou střídku, promíchejte a nechte bez poklice zvolna vařit, dokud maso zcela nezměkne a omáčka se přirozeně nezahustí.",
      "Na závěr přidejte zbývající prolisovaný česnek a v dlaních promnutou sušenou majoránku. Krátce provařte, stáhněte z ohně a nechte chvíli odležet."
    ],
    "applianceTips": "Pro dokonalou distribuci tepla použijte těžký litinový hrnec. Pokud vaříte na indukci, udržujte stabilní nízký výkon pro pozvolné tažení masa, které zabrání jeho vysušení.",
    "expertJustification": "Postup byl upraven podle tradičních kulinářských metod. Vynechali jsme netradiční marinování v syrovátce a nahradili ho klasickým základem z pomalu karamelizované cibule. Množství surovin bylo standardizováno pro běžnou domácí kuchyni a časy odpovídají přirozenému změknutí hovězí kližky bez zbytečného převaření.",
    "applianceType": "Litinový hrnec",
    "cookingTime": "150 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "gen-1782448905657",
    "updatedAt": "2026-08-02T22:46:50.667Z",
    "estimatedCookingTime": "2 hodiny"
  },
  {
    "title": "Krkonošské kyselo",
    "summary": "Tradiční polévka z žitného kvásku, lesních hub a brambor, zjemněná smetanou a doplněná nadýchanými míchanými vejci. Vyniká vyváženou kyselostí a dokonale krémovou strukturou.",
    "ingredients": [
      "[Kvasový základ]",
      "200 g chlebového žitného kvasu",
      "500 ml vlažné vody",
      "[Polévkový základ]",
      "30 g sušených lesních hub",
      "500 g brambor (nakrájených na kostky)",
      "1 l houbového nebo zeleninového vývaru",
      "3 g drceného kmínu",
      "10 g soli",
      "[Vajíčka a dokončení]",
      "4 ks vajec",
      "40 g másla",
      "150 ml zakysané smetany nebo šlehačky"
    ],
    "instructions": [
      "Aktivní žitný kvásek důkladně rozšlehejte ve vlažné vodě a nechte krátce v teple nastartovat.",
      "Brambory uvařte v osolené vodě ve slupce do měkka, poté je nechte zchladnout, oloupejte a nakrájejte na úhledné kostky.",
      "Do hrnce s horkým zeleninovým vývarem přidejte předem namočené sušené houby včetně tekutiny, ve které se máčely, a drcený kmín.",
      "Do teplého vývaru za stálého šlehání metličkou pomalu vlévejte připravený kvásek, přiveďte k varu, ihned snižte teplotu a za občasného míchání nechte mírně probublávat, aby se škroby plně provařily a polévka ztratila syrovou moučnou chuť.",
      "Na pánvi rozpusťte máslo a pomalu na něm orestujte nadrobno nakrájenou žlutou cibuli dosklovata.",
      "K cibuli přidejte vyklepnutá vejce, jemně osolte a na mírném ohni umíchejte do sametové, krémové konzistence.",
      "Do řádně provařené polévky vlijte smetanu ke šlehání, podle chuti dosolte a nechte již jen krátce přejít varem pro spojení chutí.",
      "Do hlubokých talířů rozdělte teplé nakrájené brambory, přelijte je horkým kyselem a navrch položte čerstvou porci krémových míchaných vajec."
    ],
    "applianceTips": "Pro dokonalou kontrolu teploty při dlouhém provařování kvásku využijte indukční varnou desku nastavenou na nízký výkon (přibližně 85 až 90 stupňů Celsia). Použití hrnce se silným sendvičovým dnem účinně zabrání přichytávání žitného škrobu k povrchu.",
    "expertJustification": "Doba varu kvásku byla upravena na nezbytných 25 až 30 minut, což odpovídá pekařským a kulinářským standardům pro úplné odbourání chuti syrové mouky a optimální zhoustnutí škrobů. Brambory uvařené samostatně ve slupce si uchovají pevnost a neuvolní do polévky přebytečný volný škrob. Oddělená příprava vajec na másle při nízké teplotě zajišťuje jejich maximální vláčnost a zabraňuje sražení v kyselém prostředí polévky.",
    "applianceType": "Indukční varná deska a pánev",
    "cookingTime": "60 min",
    "difficulty": "Střední",
    "category": "Polévky",
    "id": "gen-1781777007027",
    "estimatedCookingTime": "30 min",
    "updatedAt": "2026-08-02T22:46:50.667Z"
  },
  {
    "title": "Kuře na paprice",
    "summary": "Klasické kuře na paprice připravené metodou řízeného dušení pro dosažení maximální šťavnatosti a dokonalé emulze.",
    "ingredients": [
      "[Maso a základ]",
      "1 kg kuřecích stehen nebo prsou",
      "200 g cibule",
      "50 g vepřového sádla nebo másla",
      "25 g mleté sladké papriky",
      "750 ml kuřecího vývaru",
      "[Omáčka a zjemnění]",
      "200 g zakysané smetany (18%)",
      "15 g hladké mouky",
      "30 g studeného másla",
      "5 g soli",
      "2 g čerstvě mletého černého pepře"
    ],
    "instructions": [
      "Maso očistěte, osušte a z obou stran okořeňte solí a pepřem.",
      "V hrnci rozpalte přepuštěné máslo a maso orestujte ze všech stran 8 minut do zlatavé barvy, poté vyjměte.",
      "Do výpeku přidejte najemno nakrájenou cibuli a restujte 10 minut za občasného míchání, dokud není sklovitá a zlatavá.",
      "Hrnec sejměte z tepelného zdroje, vmíchejte papriku a nechte 30 sekund rozvonět.",
      "Zalijte vývarem, vraťte maso do hrnce a duste pod poklicí při nízké teplotě 60 minut.",
      "Maso vyjměte a v misce prošlehejte smetanu ke šlehání s moukou na hladkou směs.",
      "Smetanovou směs vlijte do hrnce a provařte 15 minut za občasného míchání.",
      "Omáčku stáhněte z ohně, vmíchejte zakysanou smetanu a pomocí ponorného mixéru rozmixujte do hladké textury.",
      "Nakonec do omáčky zašlehejte kostky studeného másla pro dosažení lesku a jemnosti.",
      "Vraťte maso do omáčky a prohřívejte 5 minut před podáváním."
    ],
    "applianceTips": "V multifunkčním hrnci využijte funkci Sauté pro restování masa a cibule, následně přepněte na režim Slow Cook pro dušení. Závěrečnou emulgaci máslem provádějte vždy mimo přímý zdroj tepla pro zachování stability omáčky.",
    "expertJustification": "Postup byl optimalizován z hlediska tepelné kinetiky. Prodloužení doby restování cibule zajistí hlubší chuťový základ (Maillardova reakce), zatímco řízené provaření smetany s moukou zaručuje správnou gelovatění škrobů bez rizika připálení.",
    "applianceType": "Multifunkční hrnec",
    "cookingTime": "120 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "gen-1783887414122",
    "updatedAt": "2026-08-02T22:46:50.667Z",
    "estimatedCookingTime": "113 min"
  },
  {
    "title": "Kuře z jednoho pekáče",
    "summary": "Dokonale šťavnaté kuře s bramborami, připravené s jasně rozčleněnými surovinami pro mokré nasolení, pečení i finální marinování.",
    "ingredients": [
      "[Osmóza / Slaný nálev]",
      "1 l studená voda",
      "60 g sůl",
      "5 ks kuličky nového koření",
      "10 ks kuličky černého pepře",
      "2 ks bobkový list",
      "[Maso a brambory]",
      "4 ks celá kuřecí stehna s kůží a kostí",
      "800 g brambory (varný typ B)",
      "2 ks střední cibule",
      "2 lžíce řepkový olej",
      "1 lžička sůl",
      "1 lžička drcený kmín",
      "[Marináda na kuře]",
      "2 lžíce slunečnicový olej",
      "1 lžíce med",
      "1.5 lžíce přírodně fermentovaná sójová omáčka",
      "1 lžíce citronová šťáva",
      "2 stroužky česnek",
      "1 lžička mletá sladká paprika",
      "0.5 lžičky čerstvě mletý černý pepř"
    ],
    "instructions": [
      "V hrnci smíchejte studenou vodu, sůl, nové koření, černý pepř a bobkový list pro přípravu nálevu. Směs přiveďte k varu, dokud se krystaly soli zcela nerozpustí a koření neuvolní své aromatické silice. Poté lák nechte úplně vychladnout na pokojovou teplotu.",
      "Do zcela studeného slaného nálevu ponořte očištěná kuřecí stehna. Nádobu zakryjte fólií a uložte do chladničky na čtyři hodiny, aby proces osmózy rovnoměrně prosolil maso až ke kosti.",
      "Po uplynutí doby stehna vyjměte z láku, odstraňte ulpělé koření a povrch masa důkladně vysušte papírovou utěrkou. Položte je kůží nahoru na mřížku a nechte v chladničce volně oschnout bez zakrytí po dobu jedné hodiny, což dokonale dehydratuje kůži.",
      "Troubu předehřejte na 180 °C na režim horkého vzduchu s přidanou párou. Brambory nakrájejte na měsíčky a cibuli na klínky. V pekáči je promíchejte s řepkovým olejem, solí a drceným kmínem a rovnoměrně rozprostřete.",
      "Na připravené brambory s cibulí položte oschlá kuřecí stehna kůží nahoru. Kůži lehce potřete trochou řepkového oleje a vložte pekáč do předehřáté trouby. Pečte nejprve s aktivní párou při 180 °C po dobu 35 minut pro zachování šťavnatosti, a poté zvyšte teplotu na 200 °C na suchý horký vzduch a pečte dalších 10 minut, aby se začal vytavovat podkožní tuk.",
      "V malé misce metličkou vyšlehejte slunečnicový olej, med, přírodně fermentovanou sójovou omáčku, citronovou šťávu, utřený česnek, mletou sladkou papriku a mletý černý pepř do hladké emulze.",
      "Pekáč krátce vyjměte z trouby a zvyšte teplotu pečení na 220 °C nebo zapněte režim grilu s cirkulací vzduchu. Pomocí mašlovačky naneste medovou marinádu rovnoměrně na předpečenou kuřecí kůži. Vraťte do trouby a nechte zkaramelizovat dozlatova po dobu 5 až 7 minut. Před porcováním nechte maso krátce odpočinout."
    ],
    "applianceTips": "V parní troubě využijte v první fázi režim kombinované páry nastavené na padesát procent vlhkosti při 180 °C, což zaručí mimořádně šťavnaté maso. V horkovzdušné fritéze uložte brambory na dno koše a stehna položte na ně; díky intenzivní cirkulaci vzduchu při 190 °C dosáhnete extrémně křupavé kůže i bez dlouhého sušení v lednici.",
    "expertJustification": "Recept byl optimalizován rozdělením ingrediencí do čtyř funkčních celků: osmotický lák, základní kuře, ochucení brambor a finální marináda. Tento krok výrazně zvyšuje přehlednost při přípravě. Mokré nasolení (brining) mění strukturu masových proteinů, které lépe vážou vodu, zatímco dehydratace kůže v chladničce odstraňuje povrchovou vlhkost pro dokonalou Maillardovu reakci. Medová marináda se záměrně nanáší až na závěr, aby se zabránilo hořknutí a spálení cukrů při delším pečení.",
    "applianceType": "Parní trouba",
    "cookingTime": "6 h",
    "estimatedCookingTime": "52 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "gen-1784271338613",
    "updatedAt": "2026-08-02T22:46:50.667Z"
  },
  {
    "title": "Kynuté ovocné knedlíky",
    "summary": "Nadýchané kynuté knedlíky vařené v páře, využívající metodu prodloužené fermentace pro maximální lehkost a chuť.",
    "ingredients": [
      "[Těsto a kvásek]",
      "350 g hladké mouky",
      "200 g hrubé mouky",
      "250 ml plnotučného mléka",
      "2 ks vajec",
      "15 g cukru",
      "10 g čerstvého droždí",
      "5 g soli",
      "[Ovocná náplň]",
      "400 g čerstvého ovocného plnění (jahody, meruňky, borůvky)",
      "[Na posypání a přelití]",
      "100 g rozpuštěného másla",
      "Strouhaný tvrdý tvaroh",
      "Moučkový cukr"
    ],
    "instructions": [
      "V teplém mléce rozmíchejte droždí se špetkou cukru a nechte 20 minut pracovat na vlažném místě.",
      "Do mísy prosejte obě mouky, přidejte sůl, zbylý cukr, vejce a vzešlý kvásek. Vše propracujte v pružné těsto, které nechte v teple kynout 60 minut do zdvojnásobení objemu.",
      "Vykynuté těsto rozdělte na stejné díly, vytvarujte placky a vložte ovoce. Pevně uzavřete a nechte na válu 20 minut kynout.",
      "Připravte si parní lázeň. Knedlíky vkládejte do napařovače a vařte 10 minut. Ihned po vyjmutí propíchněte vidlicí, aby unikla pára."
    ],
    "applianceTips": "Použití parní konvekce nebo parního hrnce zajistí rovnoměrný nárůst těsta bez rizika rozmočení, které hrozí při klasickém varu ve vodě.",
    "expertJustification": "Optimalizovaná doba kynutí a teplota mléka zajišťují správnou hydrataci lepkové sítě, což vede k jemnější střídce. Krátké napařování zachovává integritu ovocné náplně a nadýchanost textury.",
    "applianceType": "Parní hrnec",
    "cookingTime": "110 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1782536913905",
    "estimatedCookingTime": "10 min",
    "updatedAt": "2026-08-02T22:46:50.667Z"
  },
  {
    "title": "Langoše",
    "summary": "Tradiční kynuté langoše připravené přímou metodou s postupným zapracováním tuku pro dosažení dokonale vláčného a pružného těsta.",
    "ingredients": [
      "[Těsto]",
      "500 g pšeničné mouky typ 00",
      "325 g plnotučného mléka",
      "15 g čerstvého droždí",
      "10 g ječné sladěnky nebo cukru",
      "10 g jemné mořské soli",
      "20 g řepkového oleje",
      "[Smažení]",
      "1000 ml řepkového oleje na smažení",
      "[Na potření a posypání]",
      "20 g česneku",
      "30 ml vody",
      "150 g Goudy",
      "150 g zakysané smetany"
    ],
    "instructions": [
      "Do mísy planetárního robotu nalijte vlažné mléko, ve kterém rozmíchejte sladěnku a rozdrobte čerstvé droždí, a nechte krátce aktivovat.",
      "Na tekutý základ nasypte mouku a navrch přidejte sůl, čímž zamezíte přímému kontaktu soli s kvasinkami.",
      "Zapněte robot na první rychlostní stupeň a hněťte, dokud se suroviny nespojí do kompaktního a hladkého těsta, které se začne odlepovat od stěn mísy.",
      "V poslední minutě hnětení za stálého chodu robotu pramínkem přilévejte olej, aby obalil lepková vlákna a dodal těstu finální elasticitu.",
      "Těsto přemístěte do nádoby a nechte v teple vykynout 60 min, dokud nezdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na bochánky, které pod utěrkou necháte krátce cca 30 min odpočinout pro snadnější vytahování.",
      "Bochánky vytvarujte do tenkých placek a ihned smažte v rozpáleném oleji dozlatova z obou stran.",
      "Hotové langoše nechte krátce okapat na papírové utěrce, potřete česnekem rozmíchaným ve vodě a podávejte se zakysanou smetanou a strouhaným sýrem."
    ],
    "applianceTips": "Při hnětení používejte planetární robot na nízké otáčky, aby se těsto nezahřálo a udrželo si svou viskozitu. Při smažení udržujte teplotu oleje stabilně kolem 175 °C pro dosažení maximální křupavosti.",
    "expertJustification": "Přímá metoda se separovaným přidáním soli a postupným zapracováním tuku zajišťuje optimální kinetiku fermentace a reologickou stabilitu lepkové sítě, což je klíčové pro snadné vytahování placek.",
    "applianceType": "Planetární robot a fritéza",
    "cookingTime": "90 min",
    "difficulty": "Střední",
    "category": "Slaná jídla bez masa",
    "id": "gen-1781590909243",
    "updatedAt": "2026-08-02T22:46:50.668Z",
    "estimatedCookingTime": "15 min"
  },
  {
    "title": "Linecké cukroví",
    "summary": "Křehké máslové cukroví s ovocnou náplní, připravené s důrazem na dokonalou texturu a stabilitu těsta.",
    "ingredients": [
      "[Linecké těsto]",
      "210 g hladké pšeničné mouky",
      "140 g studeného másla",
      "70 g moučkového cukru",
      "2 žloutky",
      "3 g kypřicího prášku bez fosfátů",
      "5 g citronové kůry",
      "1 g soli",
      "[Slepování]",
      "150 g rybízového džemu"
    ],
    "instructions": [
      "V míse prosejte mouku, moučkový cukr, sůl a kypřicí prášek.",
      "Do suché směsi zapracujte na kostičky nakrájené studené máslo a citronovou kůru pomocí kuchyňského robota s metlou typu K, dokud nevznikne jemná drobenka.",
      "Přidejte žloutky a bleskově zpracujte v hladké, homogenní těsto.",
      "Těsto zabalte do fólie a ponechte v chladu odležet 720 minut.",
      "Vychlazené těsto vyválejte na pomoučeném vále na plát o tloušťce 3 mm.",
      "Vykrájejte požadované tvary, přičemž u poloviny z nich vykrojte středový otvor.",
      "Tvary rozložte na plech s pečicím papírem a pečte 8 minut při 170 °C v horkovzdušné troubě.",
      "Upečené korpusy nechte 60 minut chladnout na mřížce.",
      "Plné tvary potřete džemem, přiklopte otvorem a případně dozdobte cukrem."
    ],
    "applianceTips": "Využijte planetární mixér na nízké otáčky, aby nedošlo k zahřátí másla třením. Stabilizace těsta v chladu před pečením je kritická pro udržení ostrých hran při vykrajování.",
    "expertJustification": "Odborná praxe vyžaduje minimálně 12 hodin odpočinku těsta v chladu pro hydrataci lepku a stabilizaci tuku, což zabraňuje deformaci při pečení. Krátký čas pečení při vyšší teplotě zajistí křehkost bez nadměrného vysušení.",
    "applianceType": "Kuchyňský robot a horkovzdušná trouba",
    "cookingTime": "800 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1783883769608",
    "updatedAt": "2026-08-02T22:46:50.668Z",
    "estimatedCookingTime": "8 min"
  },
  {
    "title": "Loupáky",
    "summary": "Tradiční sladké pečivo s vláčnou strukturou díky kombinaci másla a sádla a preciznímu procesu kynutí.",
    "ingredients": [
      "[Kynuté těsto]",
      "500 g hladké pšeničné mouky",
      "250 ml plnotučného mléka",
      "40 g másla",
      "40 g vepřového sádla",
      "70 g cukru krupice",
      "8 g soli",
      "2 žloutky",
      "21 g čerstvého droždí",
      "5 g citronové kůry",
      "[Dohotovení a posyp]",
      "1 vejce",
      "20 g máku"
    ],
    "instructions": [
      "Aktivujte droždí ve vlažném mléce s malým množstvím cukru po dobu 15 minut, aby se vytvořil silný kvásek.",
      "Do mísy prosejte mouku, přidejte sůl, zbylý cukr, citronovou kůru, žloutky, kvásek a směs másla se sádlem.",
      "Hněťte těsto mechanicky 10 minut, dokud není hladké, pružné a nelepí se na stěny nádoby.",
      "Nechte těsto kynout v teple pod utěrkou 60 minut, dokud nezdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na stejné díly a vyválejte do tenkých trojúhelníků, které srolujete od základny ke špičce do tvaru podkovy.",
      "Tvarované pečivo vyskládejte na plech a nechte finálně kynout 40 minut.",
      "Potřete rozšlehaným vejcem, posypte mákem a pečte v předehřáté troubě na 180 °C po dobu 15 minut do dosažení zlatohnědého povrchu."
    ],
    "applianceTips": "Při použití pekárny vložte nejprve tekuté suroviny, poté suché a nakonec droždí; využijte program pro hnětení a první kynutí. Parní troubu nastavte na 15 minut s nízkou vlhkostí pro optimální lesk kůrky.",
    "expertJustification": "Prodloužení doby kynutí a precizní hnětení napomáhají správnému vývoji lepkové sítě. Sádlo díky nižšímu bodu tání zajišťuje dlouhotrvající vláčnost střídky bez nutnosti chemických přísad.",
    "applianceType": "Domácí pekárna a trouba",
    "cookingTime": "140 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781776531747",
    "estimatedCookingTime": "15 min",
    "updatedAt": "2026-08-02T22:46:50.668Z"
  },
  {
    "title": "Makový koláč se švestkami",
    "summary": "Tradiční kynutý koláč s domácí makovou náplní a čerstvými švestkami, využívající moderní postupy pro dosažení maximální vláčnosti a struktury.",
    "ingredients": [
      "[Těsto]",
      "250 g hladké pšeničné mouky",
      "50 g krupicového cukru",
      "50 g změklého másla",
      "150 ml plnotučného mléka",
      "15 g čerstvého droždí",
      "1 vaječný žloutek",
      "2 g jemné soli",
      "5 g jemně nastrouhané bio citronové kůry",
      "[Maková náplň]",
      "150 g jemně mletého máku",
      "100 ml plnotučného mléka",
      "40 g krupicového cukru",
      "10 g másla",
      "15 ml tuzemského rumu",
      "1 g mleté skořice",
      "[Ovoce]",
      "300 g čerstvých švestek",
      "[Drobenka]",
      "50 g polohrubé mouky",
      "30 g krupicového cukru",
      "30 g studeného másla",
      "1 g soli",
      "[Glazura]",
      "20 g másla",
      "20 ml tuzemského rumu"
    ],
    "instructions": [
      "Droždí rozmíchejte v mléce ohřátém na 32 °C. Nechte 15 minut stát, dokud nevzejde aktivní kvásek.",
      "Během čekání připravte náplň: v rendlíku svařte mák s mlékem, cukrem, máslem a skořicí. Vařte 8 minut do zhoustnutí, vmíchejte rum a nechte vychladnout.",
      "Do mísy robotu prosejte mouku, přidejte cukr, sůl, citronovou kůru, žloutek a kvásek. Hněťte 5 minut na nízkou rychlost.",
      "Přidejte změklé máslo a hněťte dalších 7 minut, dokud není těsto dokonale elastické a odděluje se od stěn mísy.",
      "Těsto nechte 60 minut kynout pod utěrkou v teple na dvojnásobný objem.",
      "Ingredience na drobenku zpracujte konečky prstů do sypké konzistence a dejte na 15 minut vychladit do lednice.",
      "Vykynuté těsto rozprostřete do vymazané formy, rozetřete makovou náplň a poklaďte rozčtvrcenými švestkami.",
      "Povrch zasypejte drobenkou a nechte 20 minut finálně dokynout přímo ve formě.",
      "Pečte v předehřáté troubě na 180 °C po dobu 30 minut do zlatavé barvy.",
      "Ihned po vyjmutí z trouby koláč potřete směsí rozpuštěného másla a rumu."
    ],
    "applianceTips": "Pro optimální výsledek použijte funkci 'Kynutí' v parní troubě (35 °C, vlhkost 20 %), která zkrátí fermentační proces a zajistí rovnoměrnější strukturu střídy bez vysychání povrchu těsta.",
    "expertJustification": "Metoda dvojího kynutí v kombinaci s řízeným hnětením optimalizuje formování lepkové sítě pro lepší retenci oxidu uhličitého. Snížení teploty při kynutí a precizní načasování tepelné úpravy zabraňuje karamelizaci cukrů před propečením středu. Emulze rumu s máslem po upečení funguje jako hydrofobní vrstva, která brání vysychání moučných částic a zajišťuje senzorickou vláčnost po delší dobu.",
    "applianceType": "Kuchyňský robot a horkovzdušná trouba",
    "cookingTime": "155 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1783883583875",
    "updatedAt": "2026-08-02T22:46:50.668Z",
    "estimatedCookingTime": "30 min"
  },
  {
    "title": "Máslová veka",
    "summary": "Tradiční nadýchané pečivo s máslem, připravené metodou důkladného hnětení a řízeného kynutí pro optimální texturu střídky.",
    "ingredients": [
      "[Těsto]",
      "500 g hladké pšeničné mouky",
      "285 g vlažného plnotučného mléka",
      "60 g změklého másla",
      "11 g soli",
      "6 g instantního droždí"
    ],
    "instructions": [
      "Smíchejte droždí s vlažným mlékem a nechte 15 minut aktivovat v teplém prostředí.",
      "Do mísy prosejte mouku, přidejte sůl, aktivovaný kvásek a změklé máslo.",
      "Hněťte těsto pomocí kuchyňského robota 12 minut, dokud není hladké, elastické a nelepí se na stěny nádoby.",
      "Nechte těsto kynout v uzavřené nádobě 60 minut, dokud nezdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na dva stejné díly a nechte 10 minut odpočinout.",
      "Každý díl rozválejte a srolujte do pevného válečku, přičemž sváry důkladně utěsněte.",
      "Veky přeneste na plech a nechte kynout dalších 45 minut pod čistou utěrkou.",
      "Povrch jemně potřete vodou či vejcem a pečte v předehřáté troubě 25 minut při teplotě 190 °C.",
      "Po vyjmutí z trouby nechte pečivo chladnout na mřížce po dobu 30 minut."
    ],
    "applianceTips": "Pro dosažení profesionální krusty použijte v první fázi pečení vstřikování páry nebo vložte na dno trouby plech s horkou vodou na prvních 5 minut.",
    "expertJustification": "Optimalizace doby hnětení na 12 minut zajišťuje správnou vývojovou fázi lepkové sítě, zatímco prodloužená fermentace v závěrečné fázi kynutí zaručuje lehkou a nadýchanou strukturu střídky bez defektů.",
    "applianceType": "Hnětací robot a pečicí trouba",
    "cookingTime": "155 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781777771572",
    "estimatedCookingTime": "25 min",
    "updatedAt": "2026-08-02T22:46:50.668Z"
  },
  {
    "title": "Mazanec",
    "summary": "Tradiční kynuté bohaté těsto připravené procesem dlouhé fermentace pro dosažení maximální vláčnosti a struktury střídky.",
    "ingredients": [
      "[Těsto]",
      "250 g hladké mouky typ 00",
      "250 g polohrubé mouky",
      "210 ml plnotučného mléka",
      "125 g másla",
      "100 g krupicového cukru",
      "5 ks žloutků",
      "30 g čerstvého droždí",
      "5 g soli",
      "5 g citronové kůry",
      "[Přísady do těsta]",
      "50 g rozinek",
      "20 ml rumu",
      "[Posyp]",
      "30 g mandlových plátků"
    ],
    "instructions": [
      "Aktivujte kvásek smícháním droždí s vlažným mlékem a špetkou cukru, nechte pracovat 20 minut.",
      "Do mísy robotu prosejte oba druhy mouky, přidejte zbytek cukru, sůl, citronovou kůru a žloutky. Přilijte aktivovaný kvásek a hněťte 10 minut na nízký stupeň.",
      "Do vypracovaného těsta postupně zapracujte změklé máslo a hněťte dalších 12 minut, dokud není těsto elastické a nelepí se.",
      "Do hotového těsta ručně vmíchejte rozinky předem namočené v rumu a nechte v teple kynout 90 minut.",
      "Vykynuté těsto přeneste na vál, vytvarujte pevný bochník a přemístěte na plech s pečicím papírem.",
      "Nechte bochník dokynout dalších 60 minut pod utěrkou.",
      "Povrch potřete rozšlehaným žloutkem, posypte mandlemi a vložte do trouby.",
      "Pečte 10 minut při teplotě 180 °C, poté snižte teplotu na 160 °C a dopečte po dobu 35 minut do vnitřní teploty 92 °C."
    ],
    "applianceTips": "Využijte funkci kynutí v troubě při 30 °C pro stabilnější a rychlejší výsledek, následně použijte pro pečení program s mírnou vlhkostí pro dosažení tenké kůrky.",
    "expertJustification": "Změna postupu na delší hnětení a řízenou teplotu kynutí zajišťuje lepší rozvoj lepkové sítě, což je klíčové pro udržení bohatého obsahu tuku a žloutků v těstě.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "217 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781776592663",
    "estimatedCookingTime": "45 min",
    "updatedAt": "2026-08-02T22:46:50.669Z"
  },
  {
    "title": "Moravské koláčky",
    "summary": "Tradiční kynuté koláčky plněné tvarohovou směsí, povidly a zdobené máslovou drobenkou.",
    "ingredients": [
      "[Těsto]",
      "500 g hladké mouky",
      "250 g změklého másla",
      "30 g čerstvého droždí",
      "3 ks žloutků",
      "80 g krupicového cukru",
      "220 ml plnotučného mléka",
      "5 g soli",
      "[Tvarohová náplň]",
      "500 g měkkého tučného tvarohu",
      "2 ks žloutků",
      "80 g moučkového cukru",
      "5 g vanilkového extraktu",
      "[Povidlová náplň]",
      "200 g švestkových povidel",
      "[Drobenka]",
      "50 g másla",
      "50 g hrubé mouky",
      "50 g cukru krystal"
    ],
    "instructions": [
      "Z vlažného mléka, části cukru a droždí vytvořte kvásek a nechte jej v teple vzejít.",
      "Do mísy prosejte mouku, přidejte sůl, zbytek cukru, žloutky, změklé máslo a vzešlý kvásek, poté vypracujte hladké nelepivé těsto a nechte vykynout.",
      "Během kynutí vyšlehejte tvaroh se žloutky, moučkovým cukrem a vanilkovým extraktem do hladké konzistence.",
      "Promnutím másla s moukou a krystalovým cukrem připravte sypkou drobenku.",
      "Z vykynutého těsta vytvořte stejnoměrné kuličky, vyskládejte je na plech a vytvořte v nich důlky.",
      "Okraje těsta potřete vejcem, středy naplňte tvarohovou směsí a povidly, posypte drobenkou a nechte krátce dokynout.",
      "Pečte v předehřáté troubě do zlatavého zbarvení okrajů."
    ],
    "applianceTips": "Pro rovnoměrné kynutí použijte funkci 'kynutí těsta' v moderní troubě při 35 °C, která zajistí stabilní vlhkost a teplotu bez průvanu.",
    "expertJustification": "Separace ingrediencí na části dle technologického postupu zvyšuje přehlednost receptu a usnadňuje logistiku při přípravě surovin. Odstranění všech aditiv zajišťuje čistou chuť přírodních surovin.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "150 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781777490075",
    "updatedAt": "2026-08-02T22:46:50.669Z",
    "estimatedCookingTime": "25 min"
  },
  {
    "id": "knedliky",
    "title": "Parní borůvkové knedlíky",
    "summary": "Tradiční kynuté knedlíky s borůvkami připravované v páře, která zajišťuje dokonalou nadýchanost a zabraňuje sražení střídky.",
    "cookingTime": "95 min",
    "difficulty": "Střední",
    "applianceType": "Thermomix / Kuchyňský robot s parním nástavcem",
    "ingredients": [
      "[Těsto a kvásek]",
      "250g polohrubé mouky",
      "120ml polotučného mléka",
      "15g čerstvého droždí",
      "1 lžíce cukru krupice",
      "1 žloutek",
      "Špetka soli",
      "[Borůvková náplň]",
      "250g čerstvých borůvek",
      "[Na přelití a podávání]",
      "100g másla",
      "Strouhaný tvrdý tvaroh na posypání",
      "Moučkový cukr na posypání"
    ],
    "instructions": [
      "Rozmíchejte droždí ve vlažném mléce s cukrem a nechte na teplém místě vzejít aktivní kvásek.",
      "Do mísy kuchyňského robota přidejte mouku, žloutek, špetku soli a vzešlý kvásek. Pomocí hnětacího háku vypracujte hladké, elastické těsto, které se nelepí na stěny nádoby.",
      "Těsto zakryjte utěrkou a nechte v teple kynout, dokud nezdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na stejné díly. Každý kousek dlaní zploštěte, naplňte borůvkami, pečlivě zabalte do kuličky a spoj důkladně utěsněte.",
      "Vytvarované knedlíky položte spojem dolů na pomoučenou plochu, zakryjte a nechte ještě chvíli dokynout, aby se stabilizovala jejich struktura.",
      "Do nádoby robota nalijte vodu. Parní nástavec vymažte rozpuštěným máslem a rozložte do něj knedlíky s dostatečnými rozestupy.",
      "Spusťte program parního vaření a vařte v intenzivní páře pod pokličkou. Během vaření poklici neodklápějte.",
      "Uvařené knedlíky ihned po vyjmutí propíchněte špejlí nebo vidličkou, aby se uvolnila vnitřní pára. Podávejte přelité rozpuštěným máslem, posypané strouhaným tvarohem a moučkovým cukrem."
    ],
    "applianceTips": "Při vaření v parním nástavci dbejte na to, aby knedlíky nezakryly všechny otvory pro průchod páry. Cirkulace horkého vzduchu musí být rovnoměrná pro konzistentní prohřátí těsta bez oslizlých míst.",
    "expertJustification": "Úprava časů kynutí a hnětení vychází z pekařské technologie pro kynutá těsta s vyšším obsahem tuku a žloutků. Dostatečný vývoj lepku při hnětení drží borůvkovou šťávu uvnitř a druhé kynutí zabraňuje praskání knedlíků při prudkém nárůstu teploty v páře. Zkrácení doby napařování na optimální čas zamezuje rozbřednutí střídky.",
    "isDefault": true,
    "category": "Sladká jídla a moučníky",
    "estimatedCookingTime": "12 min",
    "updatedAt": "2026-08-02T22:46:50.669Z"
  },
  {
    "title": "Piškotová roláda s malinami",
    "summary": "Lehká a pružná piškotová roláda s malinovou náplní, připravená metodou francouzského sněhu pro maximální nadýchanost.",
    "ingredients": [
      "[Piškotové těsto]",
      "180 g čerstvých vajec (6 ks, oddělené bílky a žloutky)",
      "140 g krupicového cukru",
      "100 g hladké pšeničné mouky",
      "2 g jemné mořské soli",
      "[Náplň a posyp]",
      "250 g malinového džemu (domácí, bez konzervantů)",
      "15 g moučkového cukru"
    ],
    "instructions": [
      "Troubu předehřejte na 200 °C. Plech vyložte kvalitním pečicím papírem.",
      "Bílky se solí šlehejte na střední výkon, dokud nevznikne měkká pěna. Poté postupně zašlehávejte cukr, dokud není sníh pevný, lesklý a tvoří špičky, což trvá přibližně 8 minut.",
      "Do sněhu krátce zašlehejte žloutky při nízkých otáčkách, jen aby se spojily.",
      "Prosetou mouku jemně vmíchejte do vaječné směsi ručně silikonovou stěrkou, abyste zachovali objem těsta.",
      "Těsto rozetřete na plech do stejnoměrné vrstvy a pečte 8 minut dozlatova.",
      "Ihned po upečení piškot vyklopte na utěrku posypanou moučkovým cukrem, opatrně stáhněte papír a těsto i s utěrkou zamotejte. Nechte rolovat 15 minut.",
      "Vychladlý korpus rozviňte, potřete džemem, pevně stočte a před podáváním nechte v chladu 20 minut odpočinout."
    ],
    "applianceTips": "Použijte planetární robot s balónovou metlou pro dosažení maximálního objemu sněhu. U horkovzdušné trouby snižte teplotu o 20 °C, aby nedošlo k vysušení povrchu.",
    "expertJustification": "Zkrácení doby pečení na 8 minut při vyšší teplotě zajistí, že jádro piškotu zůstane vlhké a pružné, což je klíčové pro zabránění praskání. Metoda francouzského sněhu vytváří strukturní integritu, která umožňuje piškotu držet tvar bez nutnosti použití kypřidel.",
    "applianceType": "Horkovzdušná trouba a kuchyňský robot",
    "cookingTime": "55 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1783883983238",
    "updatedAt": "2026-08-02T22:46:50.669Z",
    "estimatedCookingTime": "8 min"
  },
  {
    "title": "Pizza se sladěnkou",
    "summary": "Profesionální receptura pro autentickou pizzu s využitím sladěnky pro optimální fermentaci a dokonalou karamelizaci kůrky.",
    "ingredients": [
      "[Těsto na pizzu]",
      "500 g pšeničné mouky typu 00",
      "325 g vody o teplotě 24 °C",
      "15 g čerstvého droždí",
      "7 g ječné sladěnky",
      "15 g extra panenského olivového oleje",
      "12 g mořské soli"
    ],
    "instructions": [
      "Ve vodě rozmíchejte droždí se sladěnkou. Tuto směs vlijte k prosáté mouce a začněte hníst na nízký stupeň.",
      "Po zapracování všech tekutin přidejte sůl a olej. Hněťte při střední rychlosti, dokud není těsto hladké, lesklé a nejeví známky silné lepkové sítě.",
      "Těsto přikryjte a nechte 60 minut odpočívat při pokojové teplotě, následně jej přeložte (technika stretch and fold) a nechte dalších 60 minut kynout.",
      "Zpracované těsto rozdělte na bochníky, vložte do uzavřené nádoby a nechte zrát 12 hodin v chladu, což zajistí komplexní chuťový profil.",
      "Před pečením nechte bochníky 120 minut temperovat při pokojové teplotě, poté vytvarujte pizzy, doplňte ingrediencemi a pečte při maximální možné teplotě do zlatova."
    ],
    "applianceTips": "Pro dosažení výsledků jako z profesionální pece použijte pizza kámen nebo ocelovou desku; před pečením nechte spotřebič nahřát na maximum alespoň 60 minut.",
    "expertJustification": "Dlouhá fermentace v chladu rozkládá složité sacharidy, čímž zlepšuje stravitelnost a texturu střídky, zatímco sladěnka poskytuje přirozenou výživu kvasinkám a posiluje Maillardovu reakci při vysokých teplotách.",
    "applianceType": "Trouba s funkcí horkovzduchu a pizza kamenem",
    "cookingTime": "960 min",
    "difficulty": "Střední",
    "category": "Slaná jídla bez masa",
    "id": "gen-1781777082731",
    "estimatedCookingTime": "10 min",
    "updatedAt": "2026-08-02T22:46:50.669Z"
  },
  {
    "title": "Plněné papriky v rajské omáčce",
    "summary": "Šťavnaté plněné papriky zjemněné mléčnou panádou, pečené v aromatické rajské omáčce. Příprava trvá 40 min, samotné pečení v troubě zabere 55 min a finální dokončení s pasírováním zabere 15 min.",
    "ingredients": [
      "[Papriky a masová náplň]",
      "12 ks slovenské bílé papriky",
      "500 g mleté hovězí plece",
      "500 g mletého vepřového bůčku",
      "3 ks cibule",
      "65 g vepřového sádla",
      "130 g starší žemle",
      "160 ml plnotučného mléka",
      "2 ks vejce",
      "3 stroužky česneku",
      "8 g mleté sladké papriky",
      "3 g sušené majoránky",
      "13 g soli",
      "3 g čerstvě mletého černého pepře",
      "[Základ rajské omáčky]",
      "50 g hladké mouky",
      "110 g rajčatového protlaku",
      "1100 g pasírovaných rajčat (passata)",
      "1300 ml hovězího vývaru",
      "[Koření a dochucení omáčky]",
      "1 ks svitek skořice",
      "6 ks hřebíčku",
      "8 kuliček nového koření",
      "3 ks bobkového listu",
      "65 g krupicového cukru",
      "25 ml citronové šťávy",
      "35 g studeného másla"
    ],
    "instructions": [
      "Žemle nakrájejte na drobné kostičky, v misce je zalijte vlažným mlékem a nechte důkladně prosáknout. Následně přebytečnou tekutinu z pečiva lehce vymačkejte rukama.",
      "Na pánvi rozpusťte část připraveného sádla a nadrobno nakrájenou část cibule orestujte dosklovata. Poté ji nechte krátce zchladnout na pokojovou teplotu.",
      "Do hluboké mísy vložte mleté hovězí a vepřové maso. Přidejte vymačkané pečivo, zchladlou orestovanou cibuli, rozšlehaná vejce, utřený česnek, mletou sladkou papriku, drcenou majoránku, sůl a čerstvě mletý pepř. Směs rukama důkladně propracujte, dokud se neuvolní masové bílkoviny a nevznikne kompaktní, mírně lepivá hmota.",
      "Z omytých paprik odřízněte vršky se stopkou, opatrně vyjměte semeníky a odstraňte vnitřní žebra. Do vyčištěných paprik natlačte masovou směs. Plňte pevně, ale ne příliš silou, aby papriky při tepelné úpravě nepopraskaly. Ze zbylého masového těsta vytvarujte pevné kuličky.",
      "V silnostěnném hrnci vhodném do trouby rozpusťte zbylé sádlo, přidejte zbývající jemně nakrájenou cibuli a opečte ji dozlatova. Zaprašte hladkou moukou a za stálého míchání připravte světlou jíšku.",
      "Do jíšky přidejte rajčatový protlak a krátce ho zarestujte, aby ztratil syrovou kyselost a příjemně ztmavl. Poté za stálého šlehání metlou postupně přilévejte studená pasírovaná rajčata a teplý hovězí vývar, čímž zabráníte tvorbě nežádoucích hrudek.",
      "Do základu omáčky vložte skořici, hřebíček, nové koření a bobkové listy, ideálně uzavřené v nerezovém sítku na koření. Přiveďte k varu a opatrně do hrnce naskládejte naplněné papriky i připravené masové kuličky.",
      "Hrnec přikryjte poklicí a vložte do trouby předehřáté na statický ohřev. Pečte, dokud maso i papriky zcela nezměknou. Na posledních několik minut poklici sejměte, aby papriky získaly pěknou barvu.",
      "Uvařené papriky a kuličky opatrně vyjměte z hrnce a uchovejte v teple. Z omáčky vyndejte koření. Omáčku propasírujte přes jemné síto pro docílení sametově hladké textury. Dochuťte cukrem, solí a čerstvou citronovou šťávou. Nakonec mimo plotýnku vmíchejte kostičky ledového studeného másla, které omáčku zjemní a dodá jí nádherný lesk."
    ],
    "applianceTips": "Před vložením naplněných paprik do omáčky je můžete vyskládat do koše horkovzdušné fritézy (Air Fryer) a opékat při vysoké teplotě po dobu několika minut. Na slupce paprik se vytvoří typické hnědé puchýřky a spustí se Maillardova reakce, která dodá hotovému pokrmu hlubší uzenou chuť.",
    "expertJustification": "Podle profesionálních kulinářských standardů a fyzikálně-chemických principů vaření je nezbytné striktně oddělovat přesnou formuli (seznam ingrediencí s exaktními metrickými jednotkami) od samotného technologického postupu. Uvádění konkrétních gramáží přímo v krocích přípravy narušuje čitelnost, plynulost a zvyšuje riziko chyb při manipulaci s receptem. Všechny suroviny jsou proto detailně specifikovány v seznamu, zatímco v krocích se pracuje s jejich logickým a časovým zapojením. Recept je zcela bez chemických konzervantů a umělých dochucovadel.",
    "applianceType": "Air Fryer",
    "cookingTime": "110 min",
    "estimatedCookingTime": "70 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "recipe-ai-1785707213088",
    "updatedAt": "2026-08-02T22:46:50.670Z"
  },
  {
    "title": "Preclíky ze Sedlice",
    "summary": "Tradiční slané pečivo s vláčným středem a zlatavou kůrkou připravené pomocí dlouhého kynutí.",
    "ingredients": [
      "[Těsto]",
      "500 g hladké pšeničné mouky",
      "200 g sádla",
      "125 ml plnotučného mléka",
      "42 g čerstvého droždí",
      "10 g soli",
      "[Na potření a posyp]",
      "30 ml mléka na potření",
      "50 g máku a hrubozrnné soli na posyp"
    ],
    "instructions": [
      "Droždí rozmíchejte ve vlažném mléce a nechte krátce aktivovat, aby se vytvořil kvásek.",
      "Do mísy prosejte mouku se solí, přidejte sádlo a připravený kvásek.",
      "Hněťte těsto tak dlouho, dokud není pružné, hladké a zcela nelepivé.",
      "Zakryté těsto nechte v teple kynout, dokud zdvojnásobí svůj objem.",
      "Vykynuté těsto rozdělte na stejné části, ze kterých vyválejte prameny a vytvarujte preclíky.",
      "Preclíky vyskládejte na plech a nechte krátce dokynout před pečením.",
      "Povrch potřete mlékem, posypte mákem či hrubozrnnou solí a pečte v předehřáté troubě dozlatova."
    ],
    "applianceTips": "Využijte parní funkci trouby pro vlhkou atmosféru během prvních minut pečení, což zajistí maximální objem a křupavý povrch.",
    "expertJustification": "Zachování poměru surovin při 500 g mouky zajišťuje optimální hydrataci těsta a správnou lepkovou strukturu, která po upečení garantuje kýženou křehkost.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "150 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781777534961",
    "estimatedCookingTime": "15 min",
    "updatedAt": "2026-08-02T22:46:50.670Z"
  },
  {
    "title": "Rohlíky pšeničné",
    "summary": "Tradiční pšeničné rohlíky připravené metodou autolýzy a řízeného kynutí pro dosažení optimální struktury střídky a křupavé kůrky.",
    "ingredients": [
      "[Těsto]",
      "500 g hladké pšeničné mouky",
      "270 g vody",
      "5 g krupicového cukru",
      "12 g čerstvého droždí",
      "10 g jemné soli",
      "30 g vepřového sádla"
    ],
    "instructions": [
      "Ve vlažné vodě rozmíchejte cukr a droždí a nechte 15 minut aktivovat.",
      "Mouku smíchejte se zbytkem vody a nechte 30 minut proběhnout proces autolýzy pro lepší rozvoj lepku.",
      "Ke směsi přidejte aktivovaný kvásek a hněťte 5 minut na nízké otáčky.",
      "Přidejte sůl a změklé sádlo a pokračujte v hnětení dalších 8 minut, dokud není těsto hladké a elastické.",
      "Těsto nechte 60 minut kynout v teple, přičemž po 30 minutách proveďte překlad pro zpevnění struktury.",
      "Vykynuté těsto rozdělte na stejné díly a vytvarujte bochánky, které nechte 10 minut odpočívat pod utěrkou.",
      "Bochánky vyválejte do trojúhelníků a pevně srolujte do tvaru rohlíků.",
      "Rohlíky nechte finálně kynout na plechu 45 minut do zdvojnásobení objemu.",
      "Pečte 15 minut v troubě vyhřáté na 230 °C se zapařením pro vytvoření lesklé kůrky.",
      "Po vyjmutí nechte vychladnout na mřížce 20 minut."
    ],
    "applianceTips": "Při pečení využijte program s vysokou vlhkostí nebo vlijte 100 ml vroucí vody na spodní plech pro dosažení profesionálního lesku kůrky.",
    "expertJustification": "Zkrácení hnětení a zavedení cílené autolýzy stabilizuje lepkovou síť, což zabraňuje degradaci těsta a zajišťuje rovnoměrné kynutí bez použití aditiv.",
    "applianceType": "Parní trouba",
    "cookingTime": "183 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781436210192",
    "updatedAt": "2026-08-02T22:46:50.670Z",
    "estimatedCookingTime": "15 min"
  },
  {
    "title": "Rohlíky se sladovým výtažkem",
    "summary": "Klasické pečivo s vysokou hydratací a sladovým výtažkem pro dosažení profesionální textury střídky a křupavé kůrky.",
    "ingredients": [
      "[Těsto]",
      "500 g pšeničné mouky hladké",
      "270 g vlažné vody",
      "6 g diastatického sladového výtažku",
      "12 g čerstvého droždí",
      "10 g jemné soli",
      "30 g vepřového sádla"
    ],
    "instructions": [
      "Droždí rozmíchejte v části vlažné tekutiny a nechte 15 minut aktivovat v teplém prostředí pro vytvoření startovací kultury.",
      "Mouku smíchejte se zbylou tekutinou a sladovým výtažkem. Nechte směs 20 minut autolýzovat pro lepší hydrataci lepkových vláken.",
      "Přidejte aktivovaný kvásek a hněťte v robotu 8 minut při nízké rychlosti, dokud není těsto kompaktní.",
      "Přidejte sůl a zapracujte sádlo. Pokračujte v hnětení dalších 7 minut, dokud těsto není elastické a nelepí se na stěny mísy.",
      "Těsto nechte 60 minut kynout v uzavřené nádobě, přičemž po 30 minutách proveďte překlad pro zpevnění struktury.",
      "Vykynuté těsto rozdělte na stejné díly a vytvarujte bochánky, které nechte 10 minut odpočinout.",
      "Těsto vyválejte do trojúhelníkového tvaru a pevně srolujte do finální podoby rohlíku.",
      "Nechte rohlíky na plechu dokynout po dobu 30 minut a následně pečte v zapařené troubě."
    ],
    "applianceTips": "Pro dosažení ideální krusty předehřejte troubu na maximum a při vložení plechu využijte parní ráz nebo vlijte 50 ml vroucí vody na spodní rozpálený plech.",
    "expertJustification": "Zavedení autolýzy a dvoufázového hnětení výrazně zlepšuje tažnost těsta. Sladový výtažek podporuje enzymatickou aktivitu, která zajišťuje lepší karamelizaci kůrky bez nutnosti přidávání cukru.",
    "applianceType": "Planetární robot a horkovzdušná trouba s funkcí páry",
    "cookingTime": "150 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781775974569",
    "updatedAt": "2026-08-02T22:46:50.670Z",
    "estimatedCookingTime": "18 min"
  },
  {
    "title": "Rohlíky/housky žitno-pšeničné",
    "summary": "Řemeslné pečivo s vysokým podílem vlákniny a optimalizovanou fermentací pro dosažení nadýchané střídky.",
    "ingredients": [
      "[Těsto]",
      "350 g pšeničné hladké mouky",
      "150 g žitné chlebové mouky (lze nahradit žitnou celozrnnou moukou)",
      "300 ml vlažné vody (při použití celozrnné varianty zvyšte hydrataci na 330 ml)",
      "20 g čerstvého droždí",
      "30 g sádla",
      "10 g soli",
      "5 g medu"
    ],
    "instructions": [
      "Droždí rozpusťte ve vlažné vodě s medem a nechte vzejít, dokud nevznikne aktivní kvásek.",
      "Do mísy prosejte oba druhy mouky, přidejte sůl, připravený kvásek a rozpuštěné sádlo.",
      "Hněťte hákem na nízkou rychlost, dokud těsto není hladké a přestane se lepit na stěny mísy.",
      "Zakryté těsto nechte v teple kynout, dokud nezdvojnásobí svůj objem.",
      "Těsto rozdělte na stejnoměrné díly, vytvarujte bochánky a nechte je krátce odpočinout pod utěrkou.",
      "Vytvarujte výsledné tvary, přeneste na plech a nechte finálně nakynout.",
      "Před pečením povrch postříkejte vodou, případně posypte solí či kmínem.",
      "Pečte v předehřáté troubě se zapařením, poté teplotu snižte a dopečte dozlatova."
    ],
    "applianceTips": "Využijte program pro kynutí při 30 °C pro stabilní výsledek a funkci pečení s přidanou párou pro dosažení profesionální kůrky.",
    "expertJustification": "Zvýšení hydratace u celozrnné mouky je nezbytné kvůli vyšší absorpční schopnosti vlákniny, což zajistí, že střídka zůstane vláčná a nebude vysušená.",
    "applianceType": "Horkovzdušná trouba s funkcí páry",
    "cookingTime": "155 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1783916906147",
    "updatedAt": "2026-08-02T22:46:50.670Z",
    "estimatedCookingTime": "25 min"
  },
  {
    "title": "Sekaná",
    "summary": "Klasická domácí sekaná z hovězího a vepřového masa, optimalizovaná pro maximální šťavnatost pomocí emulgace bílkovin za studena a dvoufázového pečení.",
    "ingredients": [
      "[Masová směs]",
      "500 g mletého vepřového bůčku",
      "500 g mletého hovězího krku",
      "2 starší bílé rohlíky",
      "150 ml plnotučného mléka",
      "2 střední cibule",
      "20 g vepřového sádla",
      "4 stroužky česneku",
      "2 vejce",
      "15 g soli",
      "3 g mletého černého pepře",
      "3 g drceného kmínu",
      "4 g sušené majoránky",
      "50 ml ledové vody"
    ],
    "instructions": [
      "Smíchejte mleté maso se solí a kořením. Zakryjte nádobu a nechte směs odpočívat v chladu po dobu 30 min až 2 h, čímž zahájíte proces solné filtrace a zvýšíte vaznost masné emulze.",
      "Bílé rohlíky nakrájejte na drobné kostičky, vložte do mísy, zalijte plnotučným mlékem a nechte 10 min zcela nasáknout.",
      "Na pánvi rozpusťte vepřové sádlo a nechte na něm po dobu 5 min zesklovatět nadrobno nakrájenou cibuli. Těsně před koncem přidejte utřený česnek, nechte jej 1 min rozvonět a směs ihned stáhněte, aby zchladla pod 15 °C.",
      "K namočenému pečivu přidejte odpočinuté maso, vejce, zchladlou cibuli s česnekem a kořením. Sušenou majoránku před vhozením promněte v dlaních pro uvolnění silic.",
      "Směs začněte intenzivně hnětat. Během hnětení trvajícího 10 min až 15 min postupně přilévejte ledovou vodu, přičemž teplota masa nesmí překročit 4 °C. Hněťte, dokud se neobjeví jemná bílkovinná vlákna značící uvolnění myosinu.",
      "Masové dílo několikrát silou vyzdvihněte a uhoďte s ním o dno mísy po dobu 2 min, čímž spolehlivě vytěsníte vzduchové kapsy.",
      "Rukama namočenýma ve studené vodě vytvarujte pevnou šišku bez jakýchkoliv povrchových prasklin, položte ji do sádlem vymazaného pekáče a nechte v chladničce stabilizovat dalších 30 min.",
      "Pečte v předehřáté troubě nejprve při teplotě 120 °C po dobu 60 min, přičemž povrch pravidelně polévejte horkým výpekem. Poté zvyšte teplotu na 180 °C a dopékejte 20 min až 30 min pro docílení zlatavé kůrky, dokud vnitřní teplota v jádru nedosáhne 72 °C. Před krájením nechte sekanou 15 min odpočívat."
    ],
    "applianceTips": "Při použití kombinované parní trouby pečte v režimu s 25 % páry při teplotě 120 °C po dobu 60 min, následně přepněte na horkovzduch bez páry při 180 °C na 20 min pro vytvoření dokonalé textury kůrky bez rizika prasknutí.",
    "expertJustification": "Dodržení nízké teploty suroviny pod 4 °C během hnětení s přídavkem ledové vody je klíčové pro extrakci svalové bílkoviny myosinu, která funguje jako přírodní pojivo. Dvoufázový teplotní režim pečení (120 °C a následně 180 °C) zamezuje teplotnímu šoku, udržuje buněčné stěny neporušené a zachovává maximum šťávy uvnitř masové matrice.",
    "applianceType": "Kombinovaná parní trouba",
    "cookingTime": "175 min",
    "difficulty": "Střední",
    "category": "Maso",
    "id": "gen-1783884048202",
    "updatedAt": "2026-08-02T22:46:50.670Z",
    "estimatedCookingTime": "90 min"
  },
  {
    "title": "Škvarkové placky",
    "summary": "Tradiční vrstvené pečivo s obsahem sádla a škvarků připravené technikou studené laminace pro dosažení maximální křehkosti.",
    "ingredients": [
      "[Těsto]",
      "500 g pšeničné hladké mouky",
      "230 ml vlažného mléka",
      "20 g čerstvého droždí",
      "5 g krystalového cukru",
      "100 g vejce (2 kusy)",
      "10 g jemné soli",
      "120 g vepřových škvarků",
      "180 g vepřového sádla",
      "2 g mletého černého pepře",
      "5 g drceného kmínu",
      "[Na posypání]",
      "5 g hrubozrnné soli",
      "3 g celého kmínu"
    ],
    "instructions": [
      "Aktivujte kvasinky v mléce s cukrem po dobu 15 minut, dokud se nevytvoří stabilní pěna.",
      "Ve hnětači spojte mouku, sůl, pepř, drcený kmín, vejce, kvásek a rozpuštěné sádlo. Hněťte 10 minut do dosažení pružné konzistence.",
      "Nechte těsto fermentovat v teple 60 minut.",
      "Během kynutí zpracujte škvarky se sádlem na homogenní směs a nechte ztuhnout v chladu.",
      "Rozválejte těsto, naneste tukovou směs a proveďte překlady typu kniha celkem 3x, přičemž mezi každým překladem nechte těsto odpočívat 20 minut v chladu.",
      "Rozválejte na finální výšku, vykrojte tvary, vyznačte mřížku a nechte 20 minut finálně kynout.",
      "Povrch potřete rozšlehaným vejcem, posypte hrubou solí a kmínem a pečte 20 minut při 190 °C."
    ],
    "applianceTips": "Při pečení v horkovzdušné troubě využijte funkci napařování v prvních 5 minutách pro lepší expanzi lepkové struktury.",
    "expertJustification": "Proces laminace tuku do kynutého těsta vyžaduje udržení tuku v tuhém stavu, proto je 20minutové chlazení mezi překlady klíčové. Doba kynutí 60 minut zajistí dostatečnou produkci CO2 pro lehkou střídku.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "150 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781778421698",
    "estimatedCookingTime": "20 min",
    "updatedAt": "2026-08-02T22:46:50.671Z"
  },
  {
    "title": "Špekáčkový salát",
    "summary": "Tradiční český salát s vylepšenou texturou díky řízenému marinování cibule a harmonizaci chutí v chladu.",
    "ingredients": [
      "[Základ salátu]",
      "600 g kvalitních špekáčků",
      "200 g cibule",
      "200 g sterilovaných okurek",
      "[Zálivka a dochucení]",
      "150 g domácí majonézy",
      "30 g plnotučné hořčice",
      "20 ml worcesterové omáčky",
      "30 g kečupu",
      "15 ml vinného octa",
      "10 g cukru krupice",
      "20 ml slunečnicového oleje",
      "1 g černého pepře"
    ],
    "instructions": [
      "Špekáčky zbavte střívka, podélně rozkrojte a nakrájejte na tenké půlměsíčky.",
      "Cibuli a okurky nakrájejte ručně na drobné kostičky stejné velikosti, aby byla zachována křupavost a salát nepustil příliš mnoho tekutiny.",
      "V míse vyšlehejte olej, hořčici, worcester, kečup, ocet, cukr a pepř, dokud nevznikne hladká emulze.",
      "Do připravené emulze vložte nakrájenou cibuli a nechte ji krátce marinovat pro zjemnění její štiplavosti.",
      "Následně přidejte nakrájené špekáčky a okurky a vše důkladně promíchejte.",
      "Nakonec do směsi opatrně vmíchejte majonézu a nechte salát v chladu odpočívat, aby se chutě správně propojily."
    ],
    "applianceTips": "Namísto robotu doporučuji použití ostrého šéfkuchařského nože, který zajistí čisté řezy surovin bez zbytečného drcení vláken.",
    "expertJustification": "Změna techniky krájení z robotu na ruční zajišťuje integritu surovin, což zabraňuje uvolňování přebytečné vody a zachovává požadovanou viskozitu výsledného salátu.",
    "applianceType": "Kuchařský nůž a nerezová mísa",
    "cookingTime": "280 min",
    "difficulty": "Snadné",
    "category": "Ostatní",
    "id": "gen-1781777658404",
    "estimatedCookingTime": "20 min",
    "updatedAt": "2026-08-02T22:46:50.671Z"
  },
  {
    "id": "svickova",
    "title": "Svíčková na smetaně",
    "summary": "Klasická svíčková připravená v multifunkčním hrnci s důrazem na Maillardovu reakci a přirozené zahuštění zeleninovým základem.",
    "cookingTime": "120 min",
    "difficulty": "Střední",
    "applianceType": "Multifunkční hrnec",
    "ingredients": [
      "[Maso a prošpikovnání]",
      "800g hovězí zadní",
      "50g špek",
      "[Zeleninový základ omáčky]",
      "200g mrkev",
      "150g celer",
      "100g petržel",
      "120g cibule",
      "50g máslo",
      "[Dochucení a dokončení omáčky]",
      "30g plnotučná hořčice",
      "20ml ocet",
      "30g cukr krupice",
      "5ks nové koření",
      "10ks černý pepř",
      "4ks bobkový list",
      "500ml hovězí vývar",
      "250ml smetana ke šlehání 33%",
      "sůl",
      "pepř",
      "citrónová šťáva"
    ],
    "instructions": [
      "Hovězí maso prošpikujte úzkými hranolky špeku, osolte a opepřete.",
      "V multifunkčním hrnci na programu restování rozehřejte máslo a maso ze všech stran zatáhněte, dokud nevznikne tmavá krusta, poté maso vyjměte.",
      "Do výpeku vložte nastrouhanou zeleninu a restujte 12 minut do tmavě zlaté barvy.",
      "Přidejte cibuli, restujte další 5 minut, následně přisypte cukr a nechte ho 3 minuty karamelizovat.",
      "Vmíchejte hořčici, zastříkněte octem a nechte 2 minuty vyvařit kyselost.",
      "Vraťte maso do hrnce, přidejte koření v plátěném sáčku a zalijte vývarem.",
      "Uzavřete hrnec a vařte pod tlakem 60 minut.",
      "Po ukončení nechte tlak přirozeně klesat po dobu 20 minut.",
      "Vyjměte maso a koření, zeleninový základ rozmixujte dohladka.",
      "Vmíchejte smetanu, nechte 5 minut provařit a na závěr vmíchejte studené máslo pro finální emulzi, dochuťte solí a citrónovou šťávou."
    ],
    "applianceTips": "Tlakové vaření v multifunkčním hrnci efektivně narušuje kolagenní vazby v mase, což zajišťuje křehkost bez nutnosti dlouhého tažení na sporáku. Zeleninový základ slouží jako přirozené zahušťovadlo, proto se vyhněte použití mouky.",
    "expertJustification": "Postup reflektuje kulinářské principy Maillardovy reakce při restování zeleniny, která je esenciální pro hloubku chuti omáčky. Časy byly optimalizovány pro tlakové hrnce, kde 60 minut zajistí dokonalou texturu hovězího válečku při zachování šťavnatosti.",
    "category": "Maso",
    "isDefault": true,
    "estimatedCookingTime": "60 min",
    "updatedAt": "2026-08-02T22:46:50.671Z"
  },
  {
    "title": "Třená bábovka",
    "summary": "Tradiční bábovka s precizně vypracovanou strukturou díky emulgaci tuků a mechanickému provzdušnění těsta.",
    "ingredients": [
      "[Těsto]",
      "420 g polohrubé mouky",
      "320 g krupicového cukru",
      "5 ks vajec",
      "12 g kypřicího prášku do pečiva",
      "20 g vanilkového cukru",
      "180 g změklého másla",
      "250 ml plnotučného mléka",
      "5 g citronové kůry",
      "[Kakaová část]",
      "20 g holandského kakaa"
    ],
    "instructions": [
      "Při teplotě 22 °C vyšlehejte změklé máslo s cukrem a vanilkovým cukrem po dobu 8 minut, dokud směs nezíská světlou barvu a krémovou konzistenci.",
      "Postupně do směsi zašlehávejte žloutky po dobu 3 minut, čímž vytvoříte stabilní emulzi.",
      "Bílky vyšlehejte se špetkou soli po dobu 5 minut na pevný, nikoliv však vysušený sníh.",
      "Do máslového základu opatrně stěrkou vmíchejte mouku prosátou s kypřicím práškem a mléko tak, aby byla směs homogenní.",
      "Na závěr jemně zapracujte sníh z bílků a citronovou kůru pomocí techniky překládání, aby nedošlo ke zhroucení struktury.",
      "Do třetiny připraveného těsta vmíchejte kakao a následně střídavě vrstvěte světlé a tmavé těsto do vymazané a vysypané formy.",
      "Vložte do předehřáté trouby a pečte 50 minut při teplotě 170 °C, přičemž po 40 minutách provedete test špejlí pro kontrolu propečení středu."
    ],
    "applianceTips": "Využijte planetární mixér pro šlehání máslového základu na střední rychlost. Pokud disponujete horkovzdušnou funkcí, nastavte teplotu na 160 °C pro rovnoměrnější distribuci tepla v celém objemu formy.",
    "expertJustification": "Změny reflektují technologický postup 'creaming method', kde správná emulgace tuku a cukru zásadně ovlivňuje pórovitost výsledného moučníku. Časy byly upraveny dle standardů cukrářské praxe pro dosažení maximálního objemu bez nutnosti přidaných chemických stabilizátorů.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "70 min",
    "difficulty": "Střední",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1781848561960",
    "estimatedCookingTime": "50 min",
    "updatedAt": "2026-08-02T22:46:50.671Z"
  },
  {
    "title": "Tvarohový koláč",
    "summary": "Vláčný tvarohový dezert připravený pomocí šetrného pečení, který využívá přirozenou emulgaci vajec pro dosažení nadýchané struktury.",
    "ingredients": [
      "[Tvarohová hmota]",
      "500 g plnotučný hrudkovitý tvaroh",
      "150 g vejce (3 kusy velikosti M)",
      "65 g máslo",
      "150 g moučkový cukr",
      "10 g vanilkový cukr",
      "45 g dětská krupička",
      "8 g kypřicí prášek do pečiva",
      "1 g sůl"
    ],
    "instructions": [
      "Troubu předehřejte na 170 °C a dortovou formu ošetřete tukem a krupičkou pro zajištění rovnoměrné kůrky.",
      "V kuchyňském robotu šlehejte vejce s oběma druhy cukru po dobu 8 minut, dokud směs nezíská hustou, světlou konzistenci s vysokým objemem.",
      "Během šlehání vajec za stálého míchání vlijte zchladlé rozpuštěné máslo, aby se emulze stabilizovala.",
      "V samostatné míse krátce promíchejte tvaroh s krupičkou, kypřicím práškem a solí tak, aby suroviny vytvořily homogenní základ.",
      "Tvarohovou směs opatrně vmíchejte pomocí silikonové stěrky do vyšlehané vaječné pěny, postupujte krouživými pohyby zdola nahoru, aby nedošlo k degradaci vzduchových bublin.",
      "Těsto rovnoměrně vlijte do připravené formy a pečte 40 minut, dokud koláč na povrchu nezíská zlatavou barvu a není na dotek pružný.",
      "Po upečení nechte koláč 10 minut chladnout ve formě a následně jej vyjměte na mřížku pro dokončení procesu stabilizace struktury před krájením."
    ],
    "applianceTips": "Při použití kuchyňského robota s planetárním systémem šlehání použijte pro fázi s vejci nástavec balonová metla na vysoké otáčky. Pro závěrečné spojení s tvarohovou složkou zvolte pomalý režim nebo ruční zapracování, aby se zachovala lehkost těsta.",
    "expertJustification": "Recept byl optimalizován pro dosažení stabilní pěnové struktury bez nutnosti fermentace, která je u tvarohových koláčů typu 'cheesecake' nadbytečná. Snížením teploty na 170 °C eliminujeme riziko rychlého vysychání okrajů a umožníme postupnému vyrovnání vnitřní teploty, což vede k rovnoměrnému propečení bez popraskání povrchu.",
    "applianceType": "Horkovzdušná trouba",
    "cookingTime": "60 min",
    "difficulty": "Snadné",
    "category": "Sladká jídla a moučníky",
    "id": "gen-1781777341621",
    "estimatedCookingTime": "40 min",
    "updatedAt": "2026-08-02T22:46:50.672Z"
  },
  {
    "title": "Vánočka",
    "summary": "Tradiční máslová vánočka připravená metodou pomalého kynutí pro dosažení maximální vláčnosti a struktury střídky.",
    "ingredients": [
      "[Těsto a kvásek]",
      "250 g hladké pšeničné mouky",
      "250 g polohrubé pšeničné mouky",
      "200 ml plnotučného mléka",
      "110 g změklého másla",
      "90 g krupicového cukru",
      "4 ks žloutků",
      "30 g čerstvého droždí",
      "5 g soli",
      "5 g citronové kůry",
      "[Přísady do těsta]",
      "50 g rozinek",
      "20 ml tuzemského rumu",
      "[Potření a posyp]",
      "1 ks vejce",
      "30 g plátkových mandlí"
    ],
    "instructions": [
      "Smíchejte droždí s vlažným mlékem a trochou cukru. Nechte aktivovat 20 minut na teplém místě, dokud nevzejde kvásek.",
      "Do mísy robota prosejte mouku, přidejte zbytek cukru, sůl, citronovou kůru, žloutky, rum z rozinek a připravený kvásek.",
      "Hněťte 10 minut na nízkou rychlost, následně za stálého hnětení postupně přidávejte změklé máslo, dokud se těsto zcela neoddělí od stěn mísy.",
      "Do hotového těsta zapracujte namočené rozinky a nechte v zakryté nádobě kynout 90 minut, během čehož jednou těsto přeložte.",
      "Vykynuté těsto rozdělte na díly, vyválejte prameny a upleťte vánočku z devíti pramenů v patrech.",
      "Upletenou vánočku přeneste na plech a nechte kynout 60 minut pod utěrkou při pokojové teplotě.",
      "Povrch potřete rozšlehaným vejcem, posypte mandlemi a pečte 10 minut při teplotě 180 °C, poté snižte teplotu na 160 °C a dopečte 35 minut do dosažení vnitřní teploty 92 °C."
    ],
    "applianceTips": "Pro dosažení ideální elasticity těsta používejte kuchyňský robot s planetárním mícháním. Kynutí v parní troubě při 30 °C výrazně urychluje práci při zachování vlhkosti povrchu těsta.",
    "expertJustification": "Postupné přidávání tuku po vytvoření lepkové sítě zamezuje předčasnému obalení proteinů tukem, což umožňuje lepší hydrataci mouky a výslednou nadýchanost. Vnitřní teplota 92 °C je klíčová pro dosažení bodu želatinizace škrobů.",
    "applianceType": "Kuchyňský robot",
    "cookingTime": "215 min",
    "difficulty": "Střední",
    "category": "Pečivo",
    "id": "gen-1781776790684",
    "estimatedCookingTime": "45 min",
    "updatedAt": "2026-08-02T22:46:50.672Z"
  }
];
